# Generated by scripts/gen_sync.py from src/ksef2/_core/middlewares/async_error_format.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

from typing import final, override

import httpx

from ksef2._core.headers import KSeFHeaders
from ksef2._core.middlewares.base import BaseMiddleware
from ksef2._core.protocols import Middleware
from ksef2._core.types import Headers, JsonObject, QueryParamsInput


@final
class ErrorFormatMiddleware(BaseMiddleware):
    """Ask KSeF to return 400 and 429 errors as ``application/problem+json``.

    It sits on the KSeF API path only. Presigned storage URLs are reached through
    the transfer transport, which does not pass through it.
    """

    def __init__(self, transport: Middleware) -> None:
        self._next = transport

    @override
    def request(
        self,
        method: str,
        path: str,
        *,
        headers: Headers | None = None,
        params: QueryParamsInput | None = None,
        json: JsonObject | None = None,
        content: bytes | None = None,
        **kwargs: object,
    ) -> httpx.Response:
        return self._next.request(
            method,
            path,
            headers=KSeFHeaders.problem_details() | (headers or {}),
            params=params,
            json=json,
            content=content,
            **kwargs,
        )
