# Generated by scripts/gen_sync.py from src/ksef2/_core/middlewares/async_lifecycle.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

from dataclasses import dataclass
from typing import final, override

import httpx

from ksef2._core import exceptions
from ksef2._core.middlewares.base import BaseMiddleware
from ksef2._core.protocols import Middleware
from ksef2._core.types import Headers, JsonObject, QueryParamsInput


@dataclass(slots=True)
class ClientLifecycleState:
    closed: bool = False


@final
class ClientLifecycleMiddleware(BaseMiddleware):
    def __init__(
        self,
        transport: Middleware,
        state: ClientLifecycleState,
    ) -> None:
        self._next = transport
        self._state = state

    @override
    def request(
        self,
        method: str,
        path: str,
        *,
        headers: Headers | None = None,
        params: QueryParamsInput | None = None,
        json: JsonObject | None = None,
        content: bytes | None = None,
        **kwargs: object,
    ) -> httpx.Response:
        if self._state.closed:
            raise exceptions.KSeFClientClosedError("Client is closed.")

        return self._next.request(
            method,
            path,
            headers=headers,
            params=params,
            json=json,
            content=content,
            **kwargs,
        )
