# Generated by scripts/gen_sync.py from src/ksef2/core/middlewares/async_auth.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

from typing import final, override

import httpx

from ksef2.core.middlewares.base import BaseMiddleware
from ksef2.core.protocols import Middleware
from ksef2.core.types import Headers, JsonObject, QueryParamsInput


@final
class BearerTokenMiddleware(BaseMiddleware):
    def __init__(self, transport: Middleware, token: str) -> None:
        self._next = transport
        self._token = token

    def _merge(self, extra: Headers | None) -> Headers:
        headers = {"Authorization": f"Bearer {self._token}"}
        return headers | (extra or {})

    @override
    def request(
        self,
        method: str,
        path: str,
        *,
        headers: Headers | None = None,
        params: QueryParamsInput | None = None,
        json: JsonObject | None = None,
        content: bytes | None = None,
        **kwargs: object,
    ) -> httpx.Response:
        return self._next.request(
            method,
            path,
            headers=self._merge(headers),
            params=params,
            json=json,
            content=content,
            **kwargs,
        )
