# Generated by scripts/gen_sync.py from src/ksef2/core/middlewares/async_base.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

import abc

import httpx

from ksef2.core.types import Headers, JsonObject, QueryParamsInput


class BaseMiddleware(abc.ABC):
    @abc.abstractmethod
    def request(
        self,
        method: str,
        path: str,
        *,
        headers: Headers | None = None,
        params: QueryParamsInput | None = None,
        json: JsonObject | None = None,
        content: bytes | None = None,
    ) -> httpx.Response: ...

    def get(
        self,
        path: str,
        *,
        headers: Headers | None = None,
        params: QueryParamsInput | None = None,
    ) -> httpx.Response:
        return self.request("GET", path, headers=headers, params=params)

    def post(
        self,
        path: str,
        *,
        headers: Headers | None = None,
        params: QueryParamsInput | None = None,
        json: JsonObject | None = None,
        content: bytes | None = None,
    ) -> httpx.Response:
        return self.request(
            "POST",
            path,
            headers=headers,
            json=json,
            params=params,
            content=content,
        )

    def delete(
        self,
        path: str,
        *,
        headers: Headers | None = None,
        params: QueryParamsInput | None = None,
    ) -> httpx.Response:
        return self.request("DELETE", path, headers=headers, params=params)
