# Generated by scripts/gen_sync.py from src/ksef2/_core/async_external_transfer.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

"""Async transfers to external storage through presigned URLs."""

from typing import final
from urllib.parse import urlsplit

import httpx

from ksef2._core import exceptions
from ksef2._core.protocols import Middleware
from ksef2._core.types import Headers


@final
class ExternalTransferClient:
    """Transfer batch and export parts without KSeF response classification."""

    def __init__(self, transport: Middleware) -> None:
        self._transport = transport

    def upload_part(
        self,
        *,
        method: str,
        url: str,
        headers: Headers,
        content: bytes,
        reference_number: str,
        part_ordinal: int,
    ) -> None:
        """Upload one part and classify only external-storage failures."""
        host = urlsplit(url).hostname or "unknown"
        try:
            response = self._transport.request(
                method,
                url,
                headers=headers,
                content=content,
            )
        except httpx.TransportError as exc:
            raise exceptions.KSeFExternalTransferError(
                operation="upload",
                host=host,
                reference_number=reference_number,
                part_ordinal=part_ordinal,
                outcome_ambiguous=True,
            ) from exc

        if response.is_success:
            return

        try:
            _ = response.raise_for_status()
        except httpx.HTTPStatusError as exc:
            raise exceptions.KSeFExternalTransferError(
                operation="upload",
                host=host,
                reference_number=reference_number,
                part_ordinal=part_ordinal,
                status_code=response.status_code,
                outcome_ambiguous=False,
            ) from exc

    def download_part(
        self,
        *,
        url: str,
        reference_number: str,
        part_ordinal: int,
    ) -> bytes:
        """Download one part and classify only external-storage failures."""
        host = urlsplit(url).hostname or "unknown"
        try:
            response = self._transport.get(url)
        except httpx.TransportError as exc:
            raise exceptions.KSeFExternalTransferError(
                operation="download",
                host=host,
                reference_number=reference_number,
                part_ordinal=part_ordinal,
                outcome_ambiguous=False,
            ) from exc

        if response.is_success:
            return response.content

        try:
            _ = response.raise_for_status()
        except httpx.HTTPStatusError as exc:
            raise exceptions.KSeFExternalTransferError(
                operation="download",
                host=host,
                reference_number=reference_number,
                part_ordinal=part_ordinal,
                status_code=response.status_code,
                outcome_ambiguous=False,
            ) from exc

        raise exceptions.KSeFExternalTransferError(
            operation="download",
            host=host,
            reference_number=reference_number,
            part_ordinal=part_ordinal,
            status_code=response.status_code,
            outcome_ambiguous=False,
        )
