# Generated by scripts/gen_sync.py from src/ksef2/_clients/async_certificates.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

"""Async certificate branch client."""

from collections.abc import Generator, Iterator
from datetime import datetime
from typing import cast, final, override

from typing_extensions import deprecated

from ksef2._clients._handles import OperationHandle
from ksef2._clients._pager import Pager
from ksef2._core import exceptions
from ksef2._core.protocols import Middleware
from ksef2._domain.models.certificates import (
    CertificateEnrollmentData,
    CertificateEnrollmentResponse,
    CertificateEnrollmentStatusResponse,
    CertificateInfo,
    CertificateLimitsResponse,
    CertificateSerialNumber,
    CertificatesInfoList,
    CertificateStatusValue,
    CertificateTypeValue,
    EnrollCertificateRequest,
    QueryCertificatesRequest,
    RetrieveCertificatesRequest,
    RetrievedCertificatesList,
    RevocationReason,
    RevokeCertificateRequest,
    validate_certificate_serial_number,
)
from ksef2._domain.models.pagination import OffsetPaginationParams
from ksef2._endpoints.certificates import CertificatesEndpoints
from ksef2._infra.mappers.certificates import from_spec, to_spec


@final
class CertificateEnrollment(
    OperationHandle[
        CertificateEnrollmentStatusResponse, CertificateEnrollmentStatusResponse
    ]
):
    """Handle to a certificate enrollment that KSeF issues asynchronously.

    Returned by ``auth.certificates.enroll()``. It exposes every field of the
    enrollment response, for example ``reference_number`` and ``timestamp``, and
    ``wait()`` polls until KSeF has issued the certificate.
    ``get_enrollment_status()`` on the certificates client reads the same status
    for a reference number you stored earlier.

    Raises:
        KSeFApiError: If KSeF returns an API error response.
        KSeFValidationError: If a KSeF response cannot be parsed into SDK models.
        httpx.HTTPError: If the HTTP transport fails before KSeF returns a response.
    """

    def __init__(
        self,
        client: "CertificatesClient",
        response: CertificateEnrollmentResponse,
    ) -> None:
        """Create the handle.

        Args:
            client: Certificates client used to poll the enrollment's status.
            response: Response returned by KSeF when it accepted the enrollment.
        """
        super().__init__(response.reference_number)
        self._client = client
        self._response = response

    def __getattr__(self, name: str) -> object:
        if name in CertificateEnrollmentResponse.model_fields:
            return cast(object, getattr(self._response, name))
        raise AttributeError(
            f"{type(self).__name__!r} object has no attribute {name!r}"
        )

    @property
    def timestamp(self) -> datetime:
        """Get when KSeF accepted the enrollment request.

        Returns:
            The acceptance time reported by KSeF.
        """
        return self._response.timestamp

    @property
    def response(self) -> CertificateEnrollmentResponse:
        """Get the plain enrollment response.

        Returns:
            The data model KSeF returned when it accepted the enrollment.
        """
        return self._response

    @override
    def get_status(self) -> CertificateEnrollmentStatusResponse:
        """Fetch the enrollment's current status without waiting.

        Returns:
            The enrollment status, including the certificate serial number once issued.
        """
        return self._client.get_enrollment_status(
            reference_number=self.reference_number
        )

    @override
    def _is_pending(self, status: CertificateEnrollmentStatusResponse) -> bool:
        return status.status_code == 100

    @override
    def _check_status(self, status: CertificateEnrollmentStatusResponse) -> None:
        if status.status_code not in (100, 200):
            raise exceptions.KSeFCertificateEnrollmentFailedError(
                reference_number=self.reference_number,
                status_code=status.status_code,
                description=status.status_description,
                details=status.status_details,
            )

    @override
    def _timeout_error(self, timeout: float) -> BaseException:
        return exceptions.KSeFCertificateEnrollmentTimeoutError(
            reference_number=self.reference_number,
            timeout=timeout,
        )

    @override
    def _finish(
        self, status: CertificateEnrollmentStatusResponse
    ) -> CertificateEnrollmentStatusResponse:
        return status

    def wait(
        self,
        *,
        timeout: float = 60.0,
        poll_interval: float = 2.0,
    ) -> CertificateEnrollmentStatusResponse:
        """Poll until KSeF has issued the certificate.

        Args:
            timeout: Maximum number of seconds to wait before giving up.
            poll_interval: Delay in seconds between status checks.

        Returns:
            The final status, with the issued certificate's serial number.

        Raises:
            KSeFCertificateEnrollmentFailedError: If KSeF rejects, cancels or fails the enrollment.
            KSeFCertificateEnrollmentTimeoutError: If polling exceeds ``timeout``.
        """
        return self._wait(timeout, poll_interval)


@final
class CertificatesClient:
    """High-level API for certificate enrollment, retrieval, and search.

    Catch ``KSeFException`` for SDK-classified failures raised by this branch,
    and ``httpx.HTTPError`` for transport failures.

    Raises:
        KSeFApiError: If KSeF returns an API error response. Catch
            ``KSeFAuthError`` for authentication or authorization failures and
            ``KSeFRateLimitError`` for throttling.
        KSeFValidationError: If a KSeF response cannot be parsed into SDK models.
        httpx.HTTPError: If the HTTP transport fails before KSeF returns a response.
    """

    def __init__(self, transport: Middleware) -> None:
        """Create the client.

        Args:
            transport: Middleware chain used for requests to KSeF.
        """
        self._endpoints = CertificatesEndpoints(transport)

    def get_limits(self) -> CertificateLimitsResponse:
        """Return the effective certificate enrollment and issuance quotas.

        Returns:
            The effective certificate enrollment and issuance quotas.
        """
        return from_spec(self._endpoints.get_limits())

    def get_enrollment_data(self) -> CertificateEnrollmentData:
        """Return subject data needed to prepare a CSR for enrollment.

        Returns:
            Subject data needed to prepare a CSR for enrollment.
        """
        return from_spec(self._endpoints.get_enrollment_data())

    def enroll(
        self,
        *,
        certificate_name: str,
        certificate_type: CertificateTypeValue,
        csr: str,
        valid_from: datetime | str | None = None,
    ) -> CertificateEnrollment:
        """Request issuance of a certificate from a CSR.

        Args:
            certificate_name: Name to give the certificate.
            certificate_type: Certificate type to request, ``authentication`` or ``offline``.
            csr: PKCS#10 certificate signing request, DER-encoded and Base64-encoded.
            valid_from: Requested start of validity as a datetime or ISO 8601 string; ``None`` for immediately.

        Returns:
            A handle to the enrollment; call ``wait()`` to wait until KSeF has issued the certificate.

        Example:
            ```python
            enrollment = auth.certificates.enroll(
                certificate_name="signing", certificate_type="offline", csr=csr
            )
            status = enrollment.wait()
            print(status.certificate_serial_number)
            ```
        """
        request = EnrollCertificateRequest(
            certificate_name=certificate_name,
            certificate_type=certificate_type,
            csr=csr,
            valid_from=valid_from,
        )
        body = to_spec(request)
        return CertificateEnrollment(self, from_spec(self._endpoints.enroll(body=body)))

    def get_enrollment_status(
        self,
        *,
        reference_number: str,
    ) -> CertificateEnrollmentStatusResponse:
        """Fetch the current status of a certificate enrollment request.

        Args:
            reference_number: Reference number returned by ``enroll()``.

        Returns:
            The enrollment status, including the certificate serial number once issued.
        """
        return from_spec(
            self._endpoints.get_enrollment_status(
                reference_number=reference_number,
            )
        )

    def retrieve(
        self,
        *,
        certificate_serial_numbers: list[CertificateSerialNumber],
    ) -> RetrievedCertificatesList:
        """Download issued certificates by serial number.

        Args:
            certificate_serial_numbers: Serial numbers of the certificates to download.

        Returns:
            The requested certificates with their DER data.
        """
        request = RetrieveCertificatesRequest(
            certificate_serial_numbers=certificate_serial_numbers,
        )
        body = to_spec(request)
        return from_spec(self._endpoints.retrieve(body=body))

    def revoke(
        self,
        *,
        certificate_serial_number: CertificateSerialNumber,
        reason: RevocationReason | None = None,
    ) -> None:
        """Revoke a certificate, optionally providing a revocation reason.

        Args:
            certificate_serial_number: Serial number of the certificate to revoke.
            reason: Reason for the revocation; ``None`` to omit it.
        """
        validated_serial_number = validate_certificate_serial_number(
            certificate_serial_number
        )
        request = RevokeCertificateRequest(revocation_reason=reason)
        body = to_spec(request)
        self._endpoints.revoke(
            certificate_serial_number=validated_serial_number,
            body=body,
        )

    def _query(
        self,
        *,
        name: str | None = None,
        certificate_serial_number: CertificateSerialNumber | None = None,
        certificate_type: CertificateTypeValue | None = None,
        status: CertificateStatusValue | None = None,
        expires_after: datetime | str | None = None,
        params: OffsetPaginationParams | None = None,
    ) -> CertificatesInfoList:
        parameters = params or OffsetPaginationParams()
        request = QueryCertificatesRequest(
            certificate_serial_number=certificate_serial_number,
            name=name,
            certificate_type=certificate_type,
            status=status,
            expires_after=expires_after,
        )
        body = to_spec(request)
        spec_resp = self._endpoints.query(body=body, **parameters.to_query_params())
        return from_spec(spec_resp)

    def _pages(
        self,
        *,
        name: str | None,
        certificate_serial_number: CertificateSerialNumber | None,
        certificate_type: CertificateTypeValue | None,
        status: CertificateStatusValue | None,
        expires_after: datetime | str | None,
        params: OffsetPaginationParams | None,
    ) -> Generator[CertificatesInfoList, None]:
        current_params = params or OffsetPaginationParams()

        while True:
            response = self._query(
                name=name,
                certificate_serial_number=certificate_serial_number,
                certificate_type=certificate_type,
                status=status,
                expires_after=expires_after,
                params=current_params,
            )
            yield response

            if not response.has_more:
                break

            current_params = current_params.next_page()

    @deprecated(
        "`query()` is deprecated and will be removed in ksef2 1.10.0; "
        "use `list()` instead."
    )
    def query(
        self,
        *,
        name: str | None = None,
        certificate_serial_number: CertificateSerialNumber | None = None,
        certificate_type: CertificateTypeValue | None = None,
        status: CertificateStatusValue | None = None,
        expires_after: datetime | str | None = None,
        params: OffsetPaginationParams | None = None,
    ) -> CertificatesInfoList:
        """Deprecated: fetch one page of certificate search results.

        Deprecated:
            Will be removed in ksef2 1.10.0. Use ``list()`` instead; ``first_page()`` fetches one page.

        Args:
            name: Match this certificate name.
            certificate_serial_number: Match this certificate serial number.
            certificate_type: Match this certificate type.
            status: Match this lifecycle status.
            expires_after: Match certificates that expire after this datetime or ISO 8601 string.
            params: Page size and offset; defaults are used when ``None``.

        Returns:
            One page of certificate metadata.
        """
        return self._query(
            name=name,
            certificate_serial_number=certificate_serial_number,
            certificate_type=certificate_type,
            status=status,
            expires_after=expires_after,
            params=params,
        )

    @deprecated(
        "`all()` is deprecated and will be removed in ksef2 1.10.0; "
        "use `list()` instead."
    )
    def all(
        self,
        *,
        certificate_serial_number: CertificateSerialNumber | None = None,
        name: str | None = None,
        certificate_type: CertificateTypeValue | None = None,
        status: CertificateStatusValue | None = None,
        expires_after: datetime | str | None = None,
        params: OffsetPaginationParams | None = None,
    ) -> Iterator[CertificateInfo]:
        """Deprecated: iterate over all certificates matching the provided filters.

        Deprecated:
            Will be removed in ksef2 1.10.0. Use ``list()`` instead.

        Args:
            certificate_serial_number: Match this certificate serial number.
            name: Match this certificate name.
            certificate_type: Match this certificate type.
            status: Match this lifecycle status.
            expires_after: Match certificates that expire after this datetime or ISO 8601 string.
            params: Page size and offset of the first page; defaults are used when ``None``.

        Yields:
            Each matching certificate, across all pages.
        """
        for page in self._pages(
            name=name,
            certificate_serial_number=certificate_serial_number,
            certificate_type=certificate_type,
            status=status,
            expires_after=expires_after,
            params=params,
        ):
            for certificate in page.certificates:
                yield certificate

    def list(
        self,
        *,
        name: str | None = None,
        certificate_serial_number: CertificateSerialNumber | None = None,
        certificate_type: CertificateTypeValue | None = None,
        status: CertificateStatusValue | None = None,
        expires_after: datetime | str | None = None,
        params: OffsetPaginationParams | None = None,
    ) -> Pager[CertificateInfo]:
        """List the certificates of the authenticated context.

        Nothing is requested until the result is consumed. Iterate it for every
        matching certificate, call ``pages()`` for page-sized lists or
        ``first_page()`` for one request only.

        Args:
            name: Match this certificate name.
            certificate_serial_number: Match this certificate serial number.
            certificate_type: Match this certificate type.
            status: Match this lifecycle status.
            expires_after: Match certificates that expire after this datetime or ISO 8601 string.
            params: Page size and offset of the first page; defaults are used when ``None``.

        Returns:
            A paging object over the matching certificates.

        Example:
            ```python
            for certificate in auth.certificates.list(status="active"):
                print(certificate.certificate_serial_number)
            ```
        """

        def _certificate_pages() -> Generator[list[CertificateInfo], None]:
            for page in self._pages(
                name=name,
                certificate_serial_number=certificate_serial_number,
                certificate_type=certificate_type,
                status=status,
                expires_after=expires_after,
                params=params,
            ):
                yield page.certificates

        return Pager(_certificate_pages)
