# Generated by scripts/gen_sync.py from src/ksef2/_clients/async_certificates.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

"""Async certificate branch client."""

from collections.abc import Iterator
from datetime import datetime
from typing import final

from ksef2._core.protocols import Middleware
from ksef2._domain.models.certificates import (
    CertificateEnrollmentData,
    CertificateEnrollmentResponse,
    CertificateEnrollmentStatusResponse,
    CertificateInfo,
    CertificateLimitsResponse,
    CertificateSerialNumber,
    CertificatesInfoList,
    CertificateStatusValue,
    CertificateTypeValue,
    EnrollCertificateRequest,
    QueryCertificatesRequest,
    RetrieveCertificatesRequest,
    RetrievedCertificatesList,
    RevocationReason,
    RevokeCertificateRequest,
    validate_certificate_serial_number,
)
from ksef2._domain.models.pagination import OffsetPaginationParams
from ksef2._endpoints.certificates import CertificatesEndpoints
from ksef2._infra.mappers.certificates import from_spec, to_spec


@final
class CertificatesClient:
    """High-level API for certificate enrollment, retrieval, and search.

    Catch ``KSeFException`` for SDK-classified failures raised by this branch,
    and ``httpx.HTTPError`` for transport failures.

    Raises:
        KSeFApiError: If KSeF returns an API error response. Catch
            ``KSeFAuthError`` for authentication or authorization failures and
            ``KSeFRateLimitError`` for throttling.
        KSeFValidationError: If a KSeF response cannot be parsed into SDK models.
        httpx.HTTPError: If the HTTP transport fails before KSeF returns a response.
    """

    def __init__(self, transport: Middleware) -> None:
        """Create the client.

        Args:
            transport: Middleware chain used for requests to KSeF.
        """
        self._endpoints = CertificatesEndpoints(transport)

    def get_limits(self) -> CertificateLimitsResponse:
        """Return the effective certificate enrollment and issuance quotas.

        Returns:
            The effective certificate enrollment and issuance quotas.
        """
        return from_spec(self._endpoints.get_limits())

    def get_enrollment_data(self) -> CertificateEnrollmentData:
        """Return subject data needed to prepare a CSR for enrollment.

        Returns:
            Subject data needed to prepare a CSR for enrollment.
        """
        return from_spec(self._endpoints.get_enrollment_data())

    def enroll(
        self,
        *,
        certificate_name: str,
        certificate_type: CertificateTypeValue,
        csr: str,
        valid_from: datetime | str | None = None,
    ) -> CertificateEnrollmentResponse:
        """Request issuance of a certificate from a CSR.

        Args:
            certificate_name: Name to give the certificate.
            certificate_type: Certificate type to request, ``authentication`` or ``offline``.
            csr: PKCS#10 certificate signing request, DER-encoded and Base64-encoded.
            valid_from: Requested start of validity as a datetime or ISO 8601 string; ``None`` for immediately.

        Returns:
            The enrollment reference; poll ``get_enrollment_status()`` for the result.
        """
        request = EnrollCertificateRequest(
            certificate_name=certificate_name,
            certificate_type=certificate_type,
            csr=csr,
            valid_from=valid_from,
        )
        body = to_spec(request)
        return from_spec(self._endpoints.enroll(body=body))

    def get_enrollment_status(
        self,
        *,
        reference_number: str,
    ) -> CertificateEnrollmentStatusResponse:
        """Fetch the current status of a certificate enrollment request.

        Args:
            reference_number: Reference number returned by ``enroll()``.

        Returns:
            The enrollment status, including the certificate serial number once issued.
        """
        return from_spec(
            self._endpoints.get_enrollment_status(
                reference_number=reference_number,
            )
        )

    def retrieve(
        self,
        *,
        certificate_serial_numbers: list[CertificateSerialNumber],
    ) -> RetrievedCertificatesList:
        """Download issued certificates by serial number.

        Args:
            certificate_serial_numbers: Serial numbers of the certificates to download.

        Returns:
            The requested certificates with their DER data.
        """
        request = RetrieveCertificatesRequest(
            certificate_serial_numbers=certificate_serial_numbers,
        )
        body = to_spec(request)
        return from_spec(self._endpoints.retrieve(body=body))

    def revoke(
        self,
        *,
        certificate_serial_number: CertificateSerialNumber,
        reason: RevocationReason | None = None,
    ) -> None:
        """Revoke a certificate, optionally providing a revocation reason.

        Args:
            certificate_serial_number: Serial number of the certificate to revoke.
            reason: Reason for the revocation; ``None`` to omit it.
        """
        validated_serial_number = validate_certificate_serial_number(
            certificate_serial_number
        )
        request = RevokeCertificateRequest(revocation_reason=reason)
        body = to_spec(request)
        self._endpoints.revoke(
            certificate_serial_number=validated_serial_number,
            body=body,
        )

    def query(
        self,
        *,
        name: str | None = None,
        certificate_serial_number: CertificateSerialNumber | None = None,
        certificate_type: CertificateTypeValue | None = None,
        status: CertificateStatusValue | None = None,
        expires_after: datetime | str | None = None,
        params: OffsetPaginationParams | None = None,
    ) -> CertificatesInfoList:
        """Fetch one page of certificate search results.

        Args:
            name: Match this certificate name.
            certificate_serial_number: Match this certificate serial number.
            certificate_type: Match this certificate type.
            status: Match this lifecycle status.
            expires_after: Match certificates that expire after this datetime or ISO 8601 string.
            params: Page size and offset; defaults are used when ``None``.

        Returns:
            One page of certificate metadata.
        """
        parameters = params or OffsetPaginationParams()
        request = QueryCertificatesRequest(
            certificate_serial_number=certificate_serial_number,
            name=name,
            certificate_type=certificate_type,
            status=status,
            expires_after=expires_after,
        )
        body = to_spec(request)
        spec_resp = self._endpoints.query(body=body, **parameters.to_query_params())
        return from_spec(spec_resp)

    def all(
        self,
        *,
        certificate_serial_number: CertificateSerialNumber | None = None,
        name: str | None = None,
        certificate_type: CertificateTypeValue | None = None,
        status: CertificateStatusValue | None = None,
        expires_after: datetime | str | None = None,
        params: OffsetPaginationParams | None = None,
    ) -> Iterator[CertificateInfo]:
        """Iterate over all certificates matching the provided filters.

        Args:
            certificate_serial_number: Match this certificate serial number.
            name: Match this certificate name.
            certificate_type: Match this certificate type.
            status: Match this lifecycle status.
            expires_after: Match certificates that expire after this datetime or ISO 8601 string.
            params: Page size and offset of the first page; defaults are used when ``None``.

        Yields:
            Each matching certificate, across all pages.
        """
        current_params = params or OffsetPaginationParams()

        while True:
            response = self.query(
                name=name,
                certificate_serial_number=certificate_serial_number,
                certificate_type=certificate_type,
                status=status,
                expires_after=expires_after,
                params=current_params,
            )
            for certificate in response.certificates:
                yield certificate

            if not response.has_more:
                break

            current_params = current_params.next_page()
