# Generated by scripts/gen_sync.py from src/ksef2/_clients/async_online.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

"""Client bound to an open online invoice session."""

from types import TracebackType
from typing import cast, final, override

import httpx
from typing_extensions import deprecated

from ksef2._clients._handles import OperationHandle
from ksef2._core import exceptions
from ksef2._core.crypto import encrypt_invoice
from ksef2._core.polling import poll_until
from ksef2._core.protocols import Middleware
from ksef2._domain.models import invoices
from ksef2._domain.models.invoices import SendInvoicePayload
from ksef2._domain.models.session import (
    OnlineSessionResumeState,
    SessionInvoicesResponse,
    SessionInvoiceStatusResponse,
    SessionStatusResponse,
)
from ksef2._endpoints.invoices import InvoicesEndpoints
from ksef2._endpoints.session import SessionEndpoints
from ksef2._infra.mappers.invoices import from_spec as invoice_from_spec
from ksef2._infra.mappers.invoices import to_spec as invoice_to_spec
from ksef2._infra.mappers.sessions import from_spec as session_from_spec
from ksef2._logging import get_logger

logger = get_logger(__name__)


@final
class InvoiceSubmission(
    OperationHandle[SessionInvoiceStatusResponse, SessionInvoiceStatusResponse]
):
    """Handle to one invoice sent into an online session.

    Returned by ``session.send_invoice()``. It exposes every field of the
    submission response, for example ``reference_number``, and polls the invoice's
    processing status with ``wait()``. It keeps working after the session is
    closed, so a typical flow sends inside the ``with`` block and waits after it.

    Raises:
        KSeFApiError: If KSeF returns an API error response.
        KSeFValidationError: If a KSeF response cannot be parsed into SDK models.
        httpx.HTTPError: If the HTTP transport fails before KSeF returns a response.
    """

    def __init__(
        self,
        session: "OnlineSessionClient",
        response: invoices.SendInvoiceResponse,
    ) -> None:
        """Create the handle.

        Args:
            session: Online session the invoice was sent into.
            response: Submission response returned by KSeF.
        """
        super().__init__(response.reference_number)
        self._session = session
        self._response = response

    def __getattr__(self, name: str) -> object:
        if name in invoices.SendInvoiceResponse.model_fields:
            return cast(object, getattr(self._response, name))
        raise AttributeError(
            f"{type(self).__name__!r} object has no attribute {name!r}"
        )

    @property
    def response(self) -> invoices.SendInvoiceResponse:
        """Get the plain submission response.

        Returns:
            The data model KSeF returned when the invoice was accepted for processing.
        """
        return self._response

    @override
    def get_status(self) -> SessionInvoiceStatusResponse:
        """Fetch the invoice's current processing status without waiting.

        Returns:
            The processing status of the invoice.
        """
        return self._session._invoice_status(  # pyright: ignore[reportPrivateUsage]
            invoice_reference_number=self.reference_number
        )

    @override
    def _is_pending(self, status: SessionInvoiceStatusResponse) -> bool:
        return not status.ksef_number

    @override
    def _check_status(self, status: SessionInvoiceStatusResponse) -> None:
        if status.status.code >= 400:
            raise exceptions.KSeFInvoiceRejectedError(
                invoice_reference_number=self.reference_number,
                status=status,
            )

    @override
    def _timeout_error(self, timeout: float) -> BaseException:
        return exceptions.KSeFInvoiceProcessingTimeoutError(
            invoice_reference_number=self.reference_number,
            timeout=timeout,
        )

    @override
    def _finish(
        self, status: SessionInvoiceStatusResponse
    ) -> SessionInvoiceStatusResponse:
        return status

    def wait(
        self,
        *,
        timeout: float = 60.0,
        poll_interval: float = 2.0,
    ) -> SessionInvoiceStatusResponse:
        """Poll until KSeF assigns the invoice a final processing result.

        Args:
            timeout: Maximum number of seconds to wait before giving up.
            poll_interval: Delay in seconds between invoice status checks.

        Returns:
            The final processing status, including the invoice's KSeF number once accepted.

        Raises:
            KSeFInvoiceRejectedError: If invoice processing reaches a failed
                terminal status. It subclasses ``KSeFSessionError`` and keeps the
                status ``details`` and ``extensions``.
            KSeFInvoiceProcessingTimeoutError: If polling exceeds ``timeout``.
        """
        return self._wait(timeout, poll_interval)

    def download_upo(self) -> bytes:
        """Download the UPO of this invoice with a single request.

        KSeF issues the UPO once it has accepted the invoice. Call ``wait()``
        first, then this; it never waits or polls.

        Returns:
            The UPO as XML bytes.

        Raises:
            KSeFNotReadyError: If KSeF has not issued the UPO yet. Call ``wait()`` on this submission, then ask again.
        """
        return self._session._download_invoice_upo(  # pyright: ignore[reportPrivateUsage]
            reference_number=self.reference_number
        )


@final
class OnlineSessionClient:
    """Client bound to a single online invoice session.

    Send invoices with ``send_invoice()``, close the session by leaving the
    ``with`` block, then call ``wait()`` for the terminal session status and
    ``download_upo()`` for the session UPO.

    Catch ``KSeFException`` for SDK-classified failures raised by this session
    branch, and ``httpx.HTTPError`` for transport failures.

    Raises:
        KSeFApiError: If KSeF returns an API error response. Catch
            ``KSeFAuthError`` for authentication or authorization failures and
            ``KSeFRateLimitError`` for throttling.
        KSeFValidationError: If a KSeF response cannot be parsed into SDK models.
        KSeFClientClosedError: If an operation is attempted after closing the session.
        httpx.HTTPError: If the HTTP transport fails before KSeF returns a response.
    """

    def __init__(
        self,
        transport: Middleware,
        state: OnlineSessionResumeState,
        *,
        resumed: bool = False,
    ):
        """Create the session client.

        Args:
            transport: Middleware chain used for authenticated requests.
            state: Resume state describing the open session and its encryption keys.
            resumed: Whether the client was rebuilt from saved state. A resumed client cannot tell whether the session is still open, so ``wait()`` does not refuse to run on it.
        """
        self._transport = transport
        self._state = state
        self._invoice_eps = InvoicesEndpoints(transport)
        self._session_eps = SessionEndpoints(transport)
        self._closed = False
        self._resumed = resumed

    def _ensure_open(self) -> None:
        """Reject operations after the session client has been closed."""
        if self._closed:
            raise exceptions.KSeFClientClosedError("Session client is closed.")

    @property
    def reference_number(self) -> str:
        """Get the online session reference number.

        Returns:
            The KSeF reference number of the session.
        """
        return self._state.reference_number

    def submission(self, reference_number: str) -> InvoiceSubmission:
        """Get the handle of an invoice sent earlier in this session.

        Use it after a restart or on a resumed session to ``wait()`` for the
        invoice or ``download_upo()``. No request is made until you call one.

        Args:
            reference_number: Invoice reference number, as exposed by the handle ``send_invoice()`` returned.

        Returns:
            The invoice submission handle.
        """
        return InvoiceSubmission(
            self, invoices.SendInvoiceResponse(reference_number=reference_number)
        )

    def send_invoice(self, invoice_xml: bytes | str) -> InvoiceSubmission:
        """Encrypt and submit one invoice into the open session.

        Args:
            invoice_xml: Invoice XML, valid against the session's schema. A ``str`` is encoded as UTF-8.

        Returns:
            A handle exposing the submission's ``reference_number``. Call its ``wait()`` for the processing result and ``download_upo()`` for the invoice UPO.

        Raises:
            KSeFEncryptionError: If invoice encryption fails.

        Example:
            ```python
            with auth.online_session(form_code=FormSchema.FA3) as session:
                submission = session.send_invoice(xml)
                result = submission.wait(timeout=60)
                print(result.ksef_number)
            ```
        """
        self._ensure_open()
        xml_bytes = (
            invoice_xml.encode("utf-8") if isinstance(invoice_xml, str) else invoice_xml
        )
        encrypted = encrypt_invoice(
            xml_bytes=xml_bytes,
            key=self._state.get_aes_key_bytes(),
            iv=self._state.get_iv_bytes(),
        )
        request_body = invoice_to_spec(
            SendInvoicePayload(
                xml_bytes=xml_bytes,
                encrypted_bytes=encrypted,
            )
        )

        response_dto = self._invoice_eps.send(
            reference_number=self._state.reference_number,
            body=request_body,
        )
        return InvoiceSubmission(self, invoice_from_spec(response_dto))

    @deprecated(
        "`send_invoice_and_wait()` is deprecated and will be removed in ksef2 1.10.0; "
        "use `send_invoice().wait()` instead."
    )
    def send_invoice_and_wait(
        self,
        *,
        invoice_xml: bytes,
        timeout: float = 60.0,
        poll_interval: float = 2.0,
    ) -> SessionInvoiceStatusResponse:
        """Deprecated: submit an invoice and poll until KSeF assigns a final result.

        Deprecated:
            Will be removed in ksef2 1.10.0. Use ``send_invoice().wait()`` instead.

        Args:
            invoice_xml: Invoice XML bytes, valid against the session's schema.
            timeout: Maximum number of seconds to wait before giving up.
            poll_interval: Delay in seconds between invoice status checks.

        Returns:
            The final processing status, including the invoice's KSeF number once accepted.

        Raises:
            KSeFEncryptionError: If invoice encryption fails.
            KSeFInvoiceRejectedError: If invoice processing reaches a failed
                terminal status. It subclasses ``KSeFSessionError`` and keeps the
                status ``details`` and ``extensions``.
            KSeFInvoiceProcessingTimeoutError: If polling exceeds ``timeout``.
        """
        return self._send_invoice_and_wait(
            invoice_xml=invoice_xml, timeout=timeout, poll_interval=poll_interval
        )

    def _send_invoice_and_wait(
        self,
        *,
        invoice_xml: bytes,
        timeout: float = 60.0,
        poll_interval: float = 2.0,
    ) -> SessionInvoiceStatusResponse:
        submission = self.send_invoice(invoice_xml)
        return submission.wait(timeout=timeout, poll_interval=poll_interval)

    def get_status(self) -> SessionStatusResponse:
        """Fetch the current state of the online session.

        Returns:
            The session status, including invoice counters.
        """
        self._ensure_open()
        return self._session_status()

    def _session_status(self) -> SessionStatusResponse:
        return session_from_spec(
            self._invoice_eps.get_session_status(
                reference_number=self._state.reference_number,
            )
        )

    def list_invoices(
        self,
        *,
        page_size: int = 10,
        continuation_token: str | None = None,
    ) -> SessionInvoicesResponse:
        """Fetch one page of invoices submitted in this session.

        Args:
            page_size: Number of invoices per page (10–1000).
            continuation_token: Token from the previous page's response; ``None`` requests the first page.

        Returns:
            One page of invoices submitted in the session, with a continuation token when more exist.
        """
        self._ensure_open()
        return session_from_spec(
            self._invoice_eps.list_session_invoices(
                reference_number=self._state.reference_number,
                continuation_token=continuation_token,
                pageSize=page_size,
            )
        )

    def get_invoice_status(
        self, *, invoice_reference_number: str
    ) -> SessionInvoiceStatusResponse:
        """Fetch processing status for one invoice sent in this session.

        Args:
            invoice_reference_number: Reference number of the invoice within the session, as exposed by the handle ``send_invoice()`` returned.

        Returns:
            The processing status of the invoice.
        """
        self._ensure_open()
        return self._invoice_status(invoice_reference_number=invoice_reference_number)

    def _invoice_status(
        self, *, invoice_reference_number: str
    ) -> SessionInvoiceStatusResponse:
        return session_from_spec(
            self._invoice_eps.get_session_invoice_status(
                reference_number=self._state.reference_number,
                invoice_reference_number=invoice_reference_number,
            )
        )

    @deprecated(
        "`wait_for_invoice_ready()` is deprecated and will be removed in ksef2 1.10.0; "
        "use `send_invoice().wait()` instead."
    )
    def wait_for_invoice_ready(
        self,
        *,
        invoice_reference_number: str,
        timeout: float = 60.0,
        poll_interval: float = 2.0,
    ) -> SessionInvoiceStatusResponse:
        """Deprecated: poll invoice status until it succeeds, fails, or times out.

        Deprecated:
            Will be removed in ksef2 1.10.0. Use ``send_invoice().wait()`` instead.

        Args:
            invoice_reference_number: Reference number of the invoice within the session.
            timeout: Maximum number of seconds to wait before giving up.
            poll_interval: Delay in seconds between invoice status checks.

        Returns:
            The final processing status, including the invoice's KSeF number once accepted.

        Raises:
            KSeFInvoiceRejectedError: If invoice processing reaches a failed
                terminal status. It subclasses ``KSeFSessionError`` and keeps the
                status ``details`` and ``extensions``.
            KSeFInvoiceProcessingTimeoutError: If polling exceeds ``timeout``.
        """
        return self._wait_for_invoice_ready(
            invoice_reference_number=invoice_reference_number,
            timeout=timeout,
            poll_interval=poll_interval,
        )

    def _wait_for_invoice_ready(
        self,
        *,
        invoice_reference_number: str,
        timeout: float = 60.0,
        poll_interval: float = 2.0,
    ) -> SessionInvoiceStatusResponse:
        self._ensure_open()
        submission = InvoiceSubmission(
            self,
            invoices.SendInvoiceResponse(reference_number=invoice_reference_number),
        )
        return submission.wait(timeout=timeout, poll_interval=poll_interval)

    def list_failed_invoices(
        self,
        *,
        page_size: int = 10,
        continuation_token: str | None = None,
    ) -> SessionInvoicesResponse:
        """Fetch one page of invoices that failed within this session.

        Args:
            page_size: Number of invoices per page (10–1000).
            continuation_token: Token from the previous page's response; ``None`` requests the first page.

        Returns:
            One page of invoices that failed processing, with a continuation token when more exist.
        """
        self._ensure_open()
        return session_from_spec(
            self._invoice_eps.list_failed_session_invoices(
                reference_number=self._state.reference_number,
                continuation_token=continuation_token,
                pageSize=page_size,
            )
        )

    def download_invoice_upo(
        self,
        *,
        ksef_number: str | None = None,
        reference_number: str | None = None,
    ) -> bytes:
        """Download the UPO of one invoice accepted in this session.

        Args:
            ksef_number: KSeF number of the invoice. Pass this or ``reference_number``.
            reference_number: Reference number of the invoice within the session, as exposed by the handle ``send_invoice()`` returned. Pass this or ``ksef_number``.

        Returns:
            The UPO as XML bytes.

        Raises:
            KSeFValidationError: If both or neither of ``ksef_number`` and ``reference_number`` are given.
        """
        self._ensure_open()
        if (ksef_number is None) == (reference_number is None):
            raise exceptions.KSeFValidationError(
                "Pass exactly one of ksef_number or reference_number."
            )
        if ksef_number is not None:
            return self._invoice_eps.get_invoice_upo_by_ksef(
                reference_number=self._state.reference_number,
                ksef_number=ksef_number,
            )
        assert reference_number is not None
        return self._download_invoice_upo(reference_number=reference_number)

    def _download_invoice_upo(self, *, reference_number: str) -> bytes:
        return self._invoice_eps.get_invoice_upo_by_reference(
            reference_number=self._state.reference_number,
            invoice_reference_number=reference_number,
        )

    @deprecated(
        "`get_invoice_upo_by_ksef_number()` is deprecated and will be removed in "
        "ksef2 1.10.0; use `download_invoice_upo(ksef_number=...)` instead."
    )
    def get_invoice_upo_by_ksef_number(self, *, ksef_number: str) -> bytes:
        """Deprecated: download the invoice UPO by KSeF number.

        Deprecated:
            Will be removed in ksef2 1.10.0. Use ``download_invoice_upo(ksef_number=...)`` instead.

        Args:
            ksef_number: KSeF number of an invoice accepted in this session.

        Returns:
            The UPO as XML bytes.
        """
        return self.download_invoice_upo(ksef_number=ksef_number)

    @deprecated(
        "`get_invoice_upo_by_reference()` is deprecated and will be removed in "
        "ksef2 1.10.0; use `download_invoice_upo(reference_number=...)` instead."
    )
    def get_invoice_upo_by_reference(
        self,
        *,
        invoice_reference_number: str,
    ) -> bytes:
        """Deprecated: download the invoice UPO by session invoice reference number.

        Deprecated:
            Will be removed in ksef2 1.10.0. Use ``download_invoice_upo(reference_number=...)`` instead.

        Args:
            invoice_reference_number: Reference number of the invoice within the session.

        Returns:
            The UPO as XML bytes.
        """
        return self.download_invoice_upo(reference_number=invoice_reference_number)

    def _still_open_error(self) -> exceptions.KSeFSessionError:
        return exceptions.KSeFSessionError(
            f"Online session {self.reference_number} is still open.",
            hint=(
                "KSeF processes a session only after it is closed. Close the "
                "session by leaving its `with` block, then call `wait()`."
            ),
        )

    def _raise_if_failed(self, status: SessionStatusResponse) -> None:
        if status.status.code >= 400:
            raise exceptions.KSeFSessionError(
                "Online session processing failed: "
                f"{self.reference_number} ({status.status.code}: {status.status.description})",
                hint="See why invoices failed with `list_failed_invoices()`.",
            )

    def wait(
        self,
        *,
        timeout: float = 120.0,
        poll_interval: float = 2.0,
    ) -> SessionStatusResponse:
        """Poll until KSeF reports a terminal status for the closed session.

        KSeF processes the session only after it is closed, so call this after
        leaving the ``with`` block or calling ``close()``.

        Args:
            timeout: Maximum number of seconds to wait before giving up.
            poll_interval: Delay in seconds between session status checks.

        Returns:
            The final successful session status, including the session UPO references.

        Raises:
            KSeFSessionError: If the session is still open, or if KSeF reports a failed terminal status.
            KSeFOnlineSessionTimeoutError: If polling exceeds ``timeout``.
        """
        if not self._closed and not self._resumed:
            raise self._still_open_error()

        def _poll() -> SessionStatusResponse:
            status = self._session_status()
            self._raise_if_failed(status)
            return status

        return poll_until(
            operation=_poll,
            retry_predicate=lambda status: status.status.code < 200,
            poll_interval=poll_interval,
            timeout_seconds=timeout,
            timeout_error_factory=lambda: exceptions.KSeFOnlineSessionTimeoutError(
                reference_number=self.reference_number,
                timeout=timeout,
            ),
        )

    def download_upo(self) -> list[bytes]:
        """Download every page of the session UPO in one pass.

        Reads the session status once, resolves the UPO page references from it
        and downloads each page. It never waits or polls: call ``wait()`` first.

        Returns:
            The XML bytes of each UPO page, in order; empty if KSeF issued no UPO because no invoice was accepted.

        Raises:
            KSeFSessionError: If the session is still open.
            KSeFNotReadyError: If KSeF has not finished processing the closed session. Call ``wait()`` on the session, then ask again.
        """
        status = self._session_status()
        if status.status.code < 200 and (
            status.status.code == 100 or (not self._closed and not self._resumed)
        ):
            raise self._still_open_error()
        if status.status.code < 200:
            raise exceptions.KSeFNotReadyError(
                status_code=200,
                exception_code=exceptions.ExceptionCode.UNKNOWN_ERROR,
                message=(
                    f"KSeF has not finished processing online session "
                    f"{self.reference_number} ({status.status.code}: "
                    f"{status.status.description}), so there is no UPO yet."
                ),
                hint="Call `wait()` on the session first, then call `download_upo()` again.",
            )
        pages = status.upo.pages if status.upo else []
        return [
            self._session_eps.get_session_upo(
                reference_number=self._state.reference_number,
                upo_reference_number=page.reference_number,
            )
            for page in pages
        ]

    def close(self) -> None:
        """Terminate the online session if it is still open.

        Closing an already-closed session is a no-op. A client rebuilt from saved
        state first asks KSeF whether the session was already closed.

        Raises:
            KSeFApiError: If KSeF rejects the session termination request.
            httpx.HTTPError: If the HTTP transport fails before KSeF returns a
                response.
        """
        if self._closed:
            return

        if self._resumed and self._session_status().status.code != 100:
            self._closed = True
            return

        self._session_eps.terminate_online(
            reference_number=self._state.reference_number,
        )
        self._closed = True

    def resume_state(self) -> OnlineSessionResumeState:
        """Return the sensitive session state needed to resume later.

        Returns:
            The sensitive session state needed to resume later.
        """
        return self._state

    @deprecated(
        "`get_state()` is deprecated and will be removed in ksef2 1.10.0; "
        "use `resume_state()` instead."
    )
    def get_state(self) -> OnlineSessionResumeState:
        """Deprecated compatibility wrapper for ``resume_state()``.

        Deprecated:
            Will be removed in ksef2 1.10.0. Use ``resume_state()`` instead.

        Returns:
            The same state as ``resume_state()``.
        """
        return self.resume_state()

    def __enter__(self) -> "OnlineSessionClient":
        self._ensure_open()
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        try:
            self.close()
        except exceptions.KSeFException:
            if exc_type is None:
                raise
            logger.warning(
                "Failed to terminate KSeF session",
                reference_number=self._state.reference_number,
            )
        except httpx.HTTPError:
            if exc_type is None:
                raise
            logger.warning(
                "Transport error during session termination",
                reference_number=self._state.reference_number,
                exc_info=True,
            )
