# Generated by scripts/gen_sync.py from src/ksef2/_clients/async_session_management.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

"""Session-management branch client."""

from collections.abc import Generator, Iterator
from typing import final

from typing_extensions import deprecated

from ksef2._clients._pager import Pager
from ksef2._core.protocols import Middleware
from ksef2._domain.models.auth import (
    AuthenticationSession,
    AuthenticationSessionsResponse,
)
from ksef2._endpoints.auth import AuthEndpoints
from ksef2._infra.mappers.auth import from_spec


@final
class SessionManagementClient:
    """Manage authentication sessions opened through the auth API.

    Catch ``KSeFException`` for SDK-classified failures raised by this branch,
    and ``httpx.HTTPError`` for transport failures.

    Raises:
        KSeFApiError: If KSeF returns an API error response. Catch
            ``KSeFAuthError`` for authentication or authorization failures and
            ``KSeFRateLimitError`` for throttling.
        KSeFValidationError: If a KSeF response cannot be parsed into SDK models.
        httpx.HTTPError: If the HTTP transport fails before KSeF returns a response.
    """

    def __init__(self, transport: Middleware) -> None:
        """Create the client.

        Args:
            transport: Middleware chain used for requests to KSeF.
        """
        self._auth_ep = AuthEndpoints(transport)

    def _query(
        self,
        *,
        page_size: int | None = None,
        continuation_token: str | None = None,
    ) -> AuthenticationSessionsResponse:
        return from_spec(
            self._auth_ep.list_sessions(
                continuation_token=continuation_token,
                pageSize=page_size,
            )
        )

    def _pages(
        self, page_size: int | None
    ) -> Generator[AuthenticationSessionsResponse, None]:
        response = self._query(page_size=page_size)
        yield response

        while ct := response.continuation_token:
            response = self._query(page_size=page_size, continuation_token=ct)
            yield response

    @deprecated(
        "`query()` is deprecated and will be removed in ksef2 1.10.0; "
        "use `list()` instead."
    )
    def query(
        self,
        *,
        page_size: int | None = None,
        continuation_token: str | None = None,
    ) -> AuthenticationSessionsResponse:
        """Deprecated: fetch one page of authentication sessions.

        Deprecated:
            Will be removed in ksef2 1.10.0. Use ``list()`` instead; ``first_page()`` fetches one page.

        Args:
            page_size: Maximum number of sessions to request from KSeF.
            continuation_token: Cursor returned by a previous page.

        Returns:
            One page of authentication sessions for the current subject.
        """
        return self._query(page_size=page_size, continuation_token=continuation_token)

    @deprecated(
        "`all()` is deprecated and will be removed in ksef2 1.10.0; "
        "use `list()` instead."
    )
    def all(
        self,
        *,
        page_size: int | None = None,
    ) -> Iterator[AuthenticationSessionsResponse]:
        """Deprecated: iterate through all authentication session pages.

        Deprecated:
            Will be removed in ksef2 1.10.0. Use ``list().pages()`` instead.

        Args:
            page_size: Maximum number of sessions to request per page.

        Yields:
            Successive pages of authentication sessions until KSeF stops
            returning a continuation token.
        """
        for page in self._pages(page_size):
            yield page

    def terminate_current(self) -> None:
        """Terminate the authentication session backing the current bearer token."""
        self._auth_ep.terminate_current_session()

    def terminate(self, reference_number: str) -> None:
        """Terminate an authentication session by reference number.

        Args:
            reference_number: Reference number of the authentication session to terminate.
        """
        self._auth_ep.terminate_auth_session(reference_number=reference_number)

    @deprecated(
        "`close()` is deprecated and will be removed in ksef2 1.10.0; "
        "use `terminate()` instead."
    )
    def close(self, *, reference_number: str) -> None:
        """Deprecated: terminate an authentication session by reference number.

        Deprecated:
            Will be removed in ksef2 1.10.0. Use ``terminate()`` instead.

        Args:
            reference_number: Reference number of the authentication session to terminate.

        Returns:
            ``None`` once the session is terminated.
        """
        return self.terminate(reference_number)

    def list(self, *, page_size: int | None = None) -> Pager[AuthenticationSession]:
        """List the authentication sessions of the current subject.

        Nothing is requested until the result is consumed. Iterate it for every
        session, call ``pages()`` for page-sized lists or ``first_page()`` for one
        request only.

        Args:
            page_size: Maximum number of sessions to request per page; the KSeF default when ``None``.

        Returns:
            A paging object over the authentication sessions.

        Example:
            ```python
            for session in auth.sessions.list():
                print(session.reference_number)
            ```
        """

        def _session_pages() -> Generator[list[AuthenticationSession], None]:
            for page in self._pages(page_size):
                yield page.items

        return Pager(_session_pages)
