# Generated by scripts/gen_sync.py from src/ksef2/_clients/async_tokens.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

"""Async KSeF token branch client."""

from collections.abc import Iterator
from typing import final

from ksef2._core import exceptions
from ksef2._core.polling import poll_until
from ksef2._core.protocols import Middleware
from ksef2._domain.models.pagination import TokenListParams
from ksef2._domain.models.tokens import (
    GenerateTokenRequest,
    GenerateTokenResponse,
    QueryTokensResponse,
    TokenPermission,
    TokenStatusResponse,
)
from ksef2._endpoints.tokens import TokenEndpoints
from ksef2._infra.mappers.tokens import from_spec, to_spec


@final
class TokensClient:
    """High-level API for the KSeF token lifecycle.

    Catch ``KSeFException`` for SDK-classified failures raised by this branch,
    and ``httpx.HTTPError`` for transport failures.

    Raises:
        KSeFApiError: If KSeF returns an API error response. Catch
            ``KSeFAuthError`` for authentication or authorization failures and
            ``KSeFRateLimitError`` for throttling.
        KSeFValidationError: If a KSeF response cannot be parsed into SDK models.
        httpx.HTTPError: If the HTTP transport fails before KSeF returns a response.
    """

    def __init__(self, transport: Middleware) -> None:
        self._endpoints = TokenEndpoints(transport)

    def wait_for_activation(
        self,
        *,
        reference_number: str,
        timeout: float = 60.0,
        poll_interval: float = 1.0,
    ) -> TokenStatusResponse:
        """Wait until a generated token becomes active or reaches a terminal state.

        Call this explicitly after persisting the one-time credential returned by
        :meth:`generate`. A polling failure does not contain or recover that secret.

        Args:
            reference_number: Reference returned by :meth:`generate`.
            timeout: Maximum number of seconds to wait for activation.
            poll_interval: Delay in seconds between status checks.

        Returns:
            The first status response that reports the token as active.

        Raises:
            KSeFApiError: If activation ends in a terminal failure state.
            KSeFTokenStatusTimeoutError: If polling exceeds ``timeout``.
            httpx.HTTPError: If a status request fails at the transport boundary.
        """
        reference_number_local = reference_number

        def _poll() -> TokenStatusResponse:
            result = self.status(reference_number=reference_number_local)
            if result.status in ("failed", "revoked"):
                raise exceptions.KSeFApiError(
                    0,
                    exceptions.ExceptionCode.UNKNOWN_ERROR,
                    f"Token activation failed: status={result.status}",
                )
            return result

        return poll_until(
            operation=_poll,
            retry_predicate=lambda result: result.status != "active",
            poll_interval=poll_interval,
            timeout_seconds=timeout,
            timeout_error_factory=lambda: exceptions.KSeFTokenStatusTimeoutError(
                reference_number=reference_number_local,
                timeout=timeout,
            ),
        )

    def generate(
        self,
        *,
        permissions: list[TokenPermission],
        description: str,
    ) -> GenerateTokenResponse:
        """Create a token and immediately return its one-time credential.

        Args:
            permissions: Permissions to include in the generated token.
            description: Human-readable label shown in KSeF token listings.

        Returns:
            The token payload returned once by KSeF. Persist its secret before
            calling :meth:`wait_for_activation`.
        """
        request = GenerateTokenRequest(
            permissions=permissions,
            description=description,
        )
        body = to_spec(request)
        spec_resp = self._endpoints.generate_token(body=body)
        return from_spec(spec_resp)

    def list_page(
        self,
        *,
        continuation_token: str | None = None,
        params: TokenListParams | None = None,
    ) -> QueryTokensResponse:
        """Fetch one page of tokens using optional filters and continuation state.

        Args:
            continuation_token: Token identifying the next page to fetch.
            params: Optional filters and page size for the request.

        Returns:
            A single page of token results.
        """
        parameters = params or TokenListParams()
        spec_resp = self._endpoints.list_tokens(
            continuation_token=continuation_token, **parameters.to_query_params()
        )
        return from_spec(spec_resp)

    def list_all(
        self, *, params: TokenListParams | None = None
    ) -> Iterator[QueryTokensResponse]:
        """Iterate through all token pages until KSeF stops returning a continuation token.

        Args:
            params: Optional filters and page size applied to every request.

        Yields:
            Each page returned by the token listing endpoint.
        """
        parameters = params or TokenListParams()
        response = self.list_page(params=parameters)
        yield response

        while ct := response.continuation_token:
            response = self.list_page(params=parameters, continuation_token=ct)
            yield response

    def status(
        self,
        *,
        reference_number: str,
    ) -> TokenStatusResponse:
        """Return the current status of a token."""
        spec_resp = self._endpoints.token_status(reference_number=reference_number)
        return from_spec(spec_resp)

    def revoke(
        self,
        *,
        reference_number: str,
    ) -> None:
        """Revoke a token."""
        self._endpoints.revoke_token(reference_number=reference_number)
