# Generated by scripts/gen_sync.py from src/ksef2/_endpoints/async_peppol.py.
# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.

"""Peppol endpoints for querying Peppol service providers."""

from typing import Unpack, final

from ksef2._core import routes
from ksef2._domain.types import OffsetPaginationQueryParams
from ksef2._endpoints.base import BaseEndpoints
from ksef2._infra.schema.api import spec


@final
class PeppolEndpoints(BaseEndpoints):
    """Raw endpoints for Peppol provider lookups."""

    def query_providers(
        self,
        **params: Unpack[OffsetPaginationQueryParams],
    ) -> spec.QueryPeppolProvidersResponse:
        """Fetch one page of registered Peppol providers.

        Args:
            **params: Optional query parameters (``OffsetPaginationQueryParams``).

        Returns:
            The parsed KSeF response (``spec.QueryPeppolProvidersResponse``).
        """
        return self._parse(
            self._transport.get(
                path=routes.PeppolRoutes.QUERY_PROVIDERS,
                params=self.build_params(params),
            ),
            spec.QueryPeppolProvidersResponse,
        )
