"""Generate sync ksef2 modules from their async sources."""

import argparse
import ast
import difflib
import re
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import cast, override

import libcst as cst
from libcst.helpers import get_full_name_for_node, parse_template_module


REPO_ROOT = Path(__file__).resolve().parents[1]
HEADER_TEMPLATE = (
    "# Generated by scripts/gen_sync.py from {source_path}.\n"
    "# DO NOT EDIT BY HAND - edit the async source and run `just gen-sync`.\n\n"
)


@dataclass(frozen=True)
class GeneratedPair:
    source: Path
    target: Path


GENERATED_PAIRS: tuple[GeneratedPair, ...] = (
    # endpoints/
    GeneratedPair(
        Path("src/ksef2/endpoints/async_auth.py"), Path("src/ksef2/endpoints/auth.py")
    ),
    GeneratedPair(
        Path("src/ksef2/endpoints/async_certificates.py"),
        Path("src/ksef2/endpoints/certificates.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/endpoints/async_encryption.py"),
        Path("src/ksef2/endpoints/encryption.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/endpoints/async_invoices.py"),
        Path("src/ksef2/endpoints/invoices.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/endpoints/async_limits.py"),
        Path("src/ksef2/endpoints/limits.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/endpoints/async_peppol.py"),
        Path("src/ksef2/endpoints/peppol.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/endpoints/async_permissions.py"),
        Path("src/ksef2/endpoints/permissions.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/endpoints/async_session.py"),
        Path("src/ksef2/endpoints/session.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/endpoints/async_testdata.py"),
        Path("src/ksef2/endpoints/testdata.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/endpoints/async_tokens.py"),
        Path("src/ksef2/endpoints/tokens.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/endpoints/async_base.py"), Path("src/ksef2/endpoints/base.py")
    ),
    # core/middlewares/ and core/
    GeneratedPair(
        Path("src/ksef2/core/middlewares/async_auth.py"),
        Path("src/ksef2/core/middlewares/auth.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/core/middlewares/async_exceptions.py"),
        Path("src/ksef2/core/middlewares/exceptions.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/core/middlewares/async_lifecycle.py"),
        Path("src/ksef2/core/middlewares/lifecycle.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/core/middlewares/async_retry.py"),
        Path("src/ksef2/core/middlewares/retry.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/core/middlewares/async_base.py"),
        Path("src/ksef2/core/middlewares/base.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/core/async_protocols.py"), Path("src/ksef2/core/protocols.py")
    ),
    # clients/
    GeneratedPair(
        Path("src/ksef2/clients/async_auth.py"), Path("src/ksef2/clients/auth.py")
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_authenticated.py"),
        Path("src/ksef2/clients/authenticated.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_batch.py"), Path("src/ksef2/clients/batch.py")
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_certificates.py"),
        Path("src/ksef2/clients/certificates.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_encryption.py"),
        Path("src/ksef2/clients/encryption.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_invoice_sessions.py"),
        Path("src/ksef2/clients/invoice_sessions.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_invoices.py"),
        Path("src/ksef2/clients/invoices.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_limits.py"), Path("src/ksef2/clients/limits.py")
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_online.py"), Path("src/ksef2/clients/online.py")
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_peppol.py"), Path("src/ksef2/clients/peppol.py")
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_permissions.py"),
        Path("src/ksef2/clients/permissions.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_session_management.py"),
        Path("src/ksef2/clients/session_management.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_testdata.py"),
        Path("src/ksef2/clients/testdata.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/clients/async_tokens.py"), Path("src/ksef2/clients/tokens.py")
    ),
    # services/
    GeneratedPair(
        Path("src/ksef2/services/async_invoices.py"),
        Path("src/ksef2/services/invoices.py"),
    ),
    GeneratedPair(
        Path("src/ksef2/services/async_batch.py"), Path("src/ksef2/services/batch.py")
    ),
)

EXCLUDED: dict[Path, str] = {
    Path("src/ksef2/core/async_http.py"): (
        "structurally divergent transport ownership and close semantics"
    ),
    Path("src/ksef2/core/http.py"): (
        "structurally divergent transport ownership and close semantics"
    ),
    Path("src/ksef2/clients/async_base.py"): (
        "root client wiring differs; async owns awaitable-session helper integration"
    ),
    Path("src/ksef2/clients/base.py"): (
        "root client wiring differs; sync constructs and closes httpx.Client directly"
    ),
    Path("src/ksef2/endpoints/shared.py"): "shared helper module with no sync twin",
    Path(
        "src/ksef2/services/batch_preparation.py"
    ): "shared helper module with no sync twin",
    Path(
        "src/ksef2/services/export_parts.py"
    ): "shared helper module with no sync twin",
    Path(
        "src/ksef2/clients/_metadata_pagination.py"
    ): "shared helper module with no sync twin",
    Path("src/ksef2/clients/_async_session.py"): (
        "async-only awaitable context wrapper; sync factories return sessions directly"
    ),
    Path("src/ksef2/core/polling.py"): "shared sync and async polling implementations",
    Path("src/ksef2/core/response_errors.py"): "shared response error mapper",
}

NAME_MAP = {
    "AsyncIterator": "Iterator",
    "AsyncIterable": "Iterable",
    "AsyncGenerator": "Generator",
    "AsyncMiddleware": "Middleware",
    "AsyncBaseMiddleware": "BaseMiddleware",
    "AsyncSleep": "Sleep",
    "StopAsyncIteration": "StopIteration",
    "async_poll_until": "poll_until",
    "aclose": "close",
    "__aenter__": "__enter__",
    "__aexit__": "__exit__",
    "__anext__": "__next__",
    "__aiter__": "__iter__",
}

DOCSTRING_REPLACEMENTS = (
    ("async with", "with"),
    ("await ", ""),
    ("AsyncClient", "Client"),
    ("async context manager", "context manager"),
)

ASYNC_CLASS_RE = re.compile(r"^Async[A-Z]\w*$")
ASYNC_MODULE_RE = re.compile(r"(^|\.)async_")


def generated_files() -> tuple[Path, ...]:
    return tuple(pair.target for pair in GENERATED_PAIRS)


def resolve_pair(only: str | None) -> list[GeneratedPair]:
    if only is None:
        return list(GENERATED_PAIRS)

    selected = Path(only)
    normalized = (
        selected if not selected.is_absolute() else selected.relative_to(REPO_ROOT)
    )
    matches = [
        pair
        for pair in GENERATED_PAIRS
        if pair.source == normalized or pair.target == normalized
    ]
    if not matches:
        known = ", ".join(str(pair.source) for pair in GENERATED_PAIRS)
        raise SystemExit(
            f"Unknown generated source or target: {only}\nKnown sources: {known}"
        )
    return matches


class AsyncToSyncTransformer(cst.CSTTransformer):
    @override
    def leave_FunctionDef(
        self, original_node: cst.FunctionDef, updated_node: cst.FunctionDef
    ) -> cst.FunctionDef:
        return updated_node.with_changes(
            asynchronous=None,
            body=_rewrite_docstring_in_suite(updated_node.body),
        )

    @override
    def leave_ClassDef(
        self, original_node: cst.ClassDef, updated_node: cst.ClassDef
    ) -> cst.ClassDef:
        return updated_node.with_changes(
            body=_rewrite_docstring_in_suite(updated_node.body)
        )

    @override
    def leave_Module(
        self, original_node: cst.Module, updated_node: cst.Module
    ) -> cst.Module:
        return _rewrite_module_docstring(updated_node)

    @override
    def leave_With(self, original_node: cst.With, updated_node: cst.With) -> cst.With:
        return updated_node.with_changes(asynchronous=None)

    @override
    def leave_For(self, original_node: cst.For, updated_node: cst.For) -> cst.For:
        return updated_node.with_changes(asynchronous=None)

    @override
    def leave_Await(
        self, original_node: cst.Await, updated_node: cst.Await
    ) -> cst.BaseExpression:
        if isinstance(updated_node.expression, cst.Call) and _is_full_name(
            updated_node.expression.func, "asyncio.to_thread"
        ):
            return _unwrap_to_thread(updated_node.expression)
        return updated_node.expression

    @override
    def leave_Call(
        self, original_node: cst.Call, updated_node: cst.Call
    ) -> cst.BaseExpression:
        if (
            _is_name(updated_node.func, "_AwaitableSession")
            and len(updated_node.args) == 1
        ):
            return updated_node.args[0].value
        return updated_node

    @override
    def leave_Subscript(
        self, original_node: cst.Subscript, updated_node: cst.Subscript
    ) -> cst.BaseExpression:
        if _is_name(updated_node.value, "_AwaitableSession"):
            return _single_subscript_value(updated_node) or updated_node
        if _is_name(updated_node.value, "Awaitable"):
            return _single_subscript_value(updated_node) or updated_node
        if _is_name(updated_node.value, "Coroutine"):
            third = _nth_subscript_value(updated_node, 2)
            return third or updated_node
        return updated_node

    @override
    def leave_Attribute(
        self, original_node: cst.Attribute, updated_node: cst.Attribute
    ) -> cst.BaseExpression:
        if _is_full_name(updated_node, "asyncio.sleep"):
            return cst.Attribute(value=cst.Name("time"), attr=cst.Name("sleep"))
        return updated_node

    @override
    def leave_Annotation(
        self, original_node: cst.Annotation, updated_node: cst.Annotation
    ) -> cst.Annotation:
        if isinstance(updated_node.annotation, cst.SimpleString):
            return updated_node.with_changes(
                annotation=_rewrite_string_annotation(updated_node.annotation)
            )
        return updated_node

    @override
    def leave_Name(self, original_node: cst.Name, updated_node: cst.Name) -> cst.Name:
        return updated_node.with_changes(value=_sync_identifier(updated_node.value))

    @override
    def leave_ImportAlias(
        self, original_node: cst.ImportAlias, updated_node: cst.ImportAlias
    ) -> cst.ImportAlias:
        if _is_name(updated_node.name, "asyncio"):
            return updated_node.with_changes(name=cst.Name("time"))
        return updated_node

    @override
    def leave_ImportFrom(
        self, original_node: cst.ImportFrom, updated_node: cst.ImportFrom
    ) -> cst.ImportFrom:
        if updated_node.module is None:
            return updated_node

        module_name = get_full_name_for_node(updated_node.module)
        if module_name is None:
            return updated_node

        rewritten = _sync_module_name(module_name)
        if rewritten == module_name:
            return updated_node
        return updated_node.with_changes(module=_module_expr(rewritten))


def generate_source(pair: GeneratedPair, repo_root: Path = REPO_ROOT) -> str:
    source_path = repo_root / pair.source
    source = source_path.read_text()
    module = cst.parse_module(source)
    transformed = module.visit(AsyncToSyncTransformer())
    transformed = transformed.visit(SyncCompatibilityTransformer(pair))
    body = transformed.code
    header = HEADER_TEMPLATE.format(source_path=pair.source.as_posix())
    return header + body


class SyncCompatibilityTransformer(cst.CSTTransformer):
    def __init__(self, pair: GeneratedPair) -> None:
        super().__init__()

        self._pair = pair
        self._class_stack: list[str] = []
        self._function_stack: list[str] = []

    @property
    def _generating_invoices_service(self) -> bool:
        return self._pair.target == Path("src/ksef2/services/invoices.py")

    @override
    def visit_ClassDef(self, node: cst.ClassDef) -> bool | None:
        self._class_stack.append(node.name.value)
        return True

    @override
    def leave_ClassDef(
        self, original_node: cst.ClassDef, updated_node: cst.ClassDef
    ) -> cst.ClassDef:
        _ = self._class_stack.pop()
        return updated_node

    @override
    def visit_FunctionDef(self, node: cst.FunctionDef) -> bool | None:
        self._function_stack.append(node.name.value)
        return True

    @override
    def leave_FunctionDef(
        self, original_node: cst.FunctionDef, updated_node: cst.FunctionDef
    ) -> cst.FunctionDef:
        function_name = self._function_stack.pop()
        if (
            self._generating_invoices_service
            and self._class_stack == ["InvoicesService"]
            and function_name == "__init__"
        ):
            return updated_node.with_changes(
                params=_remove_param(updated_node.params, "download_transport")
            )
        return updated_node

    @override
    def leave_SimpleStatementLine(
        self,
        original_node: cst.SimpleStatementLine,
        updated_node: cst.SimpleStatementLine,
    ) -> cst.BaseStatement:
        if (
            self._generating_invoices_service
            and self._class_stack == ["InvoicesService"]
            and self._function_stack == ["__init__"]
            and _is_download_transport_assignment(updated_node)
        ):
            return cst.parse_statement(
                "self._download_transport = (\n"
                "    transport._next\n"
                "    if isinstance(transport, BearerTokenMiddleware)\n"
                "    else transport\n"
                ")\n"
            )
        return updated_node

    @override
    def leave_Call(
        self, original_node: cst.Call, updated_node: cst.Call
    ) -> cst.BaseExpression:
        if _is_name(updated_node.func, "InvoicesService"):
            positional = [
                index
                for index, arg in enumerate(updated_node.args)
                if arg.keyword is None and not arg.star
            ]
            if len(positional) >= 3:
                remove_index = positional[1]
                return updated_node.with_changes(
                    args=tuple(
                        arg
                        for index, arg in enumerate(updated_node.args)
                        if index != remove_index
                    )
                )
        return updated_node

    @override
    def leave_Module(
        self, original_node: cst.Module, updated_node: cst.Module
    ) -> cst.Module:
        if not self._generating_invoices_service:
            return updated_node
        import_statement = cst.parse_statement(
            "from ksef2.core.middlewares.auth import BearerTokenMiddleware\n"
        )
        return updated_node.with_changes(body=(import_statement, *updated_node.body))


def generate_formatted_source(pair: GeneratedPair, repo_root: Path = REPO_ROOT) -> str:
    return _format_source(generate_source(pair, repo_root), pair.target, repo_root)


def check_generated(pairs: Sequence[GeneratedPair], diff: bool) -> int:
    failures = 0
    for pair in pairs:
        expected = generate_formatted_source(pair)
        target_path = REPO_ROOT / pair.target
        actual = target_path.read_text()
        if actual == expected:
            continue

        failures += 1
        print(f"{pair.target} is not up to date", file=sys.stderr)
        if diff:
            _ = sys.stdout.writelines(_diff(actual, expected, pair.target))

    return 1 if failures else 0


def write_generated(pairs: Sequence[GeneratedPair]) -> None:
    written: list[Path] = []
    for pair in pairs:
        target_path = REPO_ROOT / pair.target
        _ = target_path.write_text(generate_source(pair), newline="")
        written.append(target_path)

    _run_ruff_fix(written)


def print_diffs(pairs: Sequence[GeneratedPair]) -> int:
    status = 0
    for pair in pairs:
        expected = generate_formatted_source(pair)
        actual = (REPO_ROOT / pair.target).read_text()
        if actual != expected:
            status = 1
            _ = sys.stdout.writelines(_diff(actual, expected, pair.target))
    return status


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _ = parser.add_argument(
        "--check", action="store_true", help="fail if generated files differ"
    )
    _ = parser.add_argument("--diff", action="store_true", help="print unified diffs")
    _ = parser.add_argument(
        "--only", help="generate/check one async source or sync target"
    )
    _ = parser.add_argument(
        "--print-files",
        action="store_true",
        help="print generated sync target paths, one per line",
    )
    namespace = parser.parse_args(argv)
    check = cast(bool, namespace.check)
    diff = cast(bool, namespace.diff)
    only = cast(str | None, namespace.only)
    print_files = cast(bool, namespace.print_files)

    pairs = resolve_pair(only)

    if print_files:
        for pair in pairs:
            print(pair.target.as_posix())
        return 0

    if check:
        return check_generated(pairs, diff=diff)

    if diff:
        return print_diffs(pairs)

    write_generated(pairs)
    return 0


def _sync_identifier(name: str) -> str:
    if name in NAME_MAP:
        return NAME_MAP[name]
    if ASYNC_CLASS_RE.match(name):
        return name.removeprefix("Async")
    return name


def _rewrite_string_annotation(node: cst.SimpleString) -> cst.SimpleString:
    try:
        value = cast(object, ast.literal_eval(node.value))
    except (SyntaxError, ValueError):
        return node
    if not isinstance(value, str):
        return node

    rewritten = re.sub(
        r"\bAsync[A-Z]\w*\b", lambda match: _sync_identifier(match.group()), value
    )
    for old, new in NAME_MAP.items():
        rewritten = re.sub(rf"\b{re.escape(old)}\b", new, rewritten)
    if rewritten == value:
        return node
    return cst.SimpleString(repr(rewritten))


def _sync_module_name(module_name: str) -> str:
    if module_name == "ksef2.core.async_protocols":
        return "ksef2.core.protocols"
    if ASYNC_MODULE_RE.search(module_name):
        return module_name.replace(".async_", ".")
    return module_name


def _module_expr(module_name: str) -> cst.BaseExpression:
    parsed = parse_template_module(f"from {module_name} import x\n")
    stmt = parsed.body[0]
    if not isinstance(stmt, cst.SimpleStatementLine):
        raise AssertionError(f"Could not parse import module {module_name!r}")
    import_node = stmt.body[0]
    if not isinstance(import_node, cst.ImportFrom) or import_node.module is None:
        raise AssertionError(f"Could not parse import module {module_name!r}")
    return import_node.module


def _is_name(node: cst.CSTNode, name: str) -> bool:
    return isinstance(node, cst.Name) and node.value == name


def _is_full_name(node: cst.CSTNode, name: str) -> bool:
    return get_full_name_for_node(node) == name


def _unwrap_to_thread(call: cst.Call) -> cst.Call:
    if not call.args:
        raise ValueError("asyncio.to_thread call has no callable argument")
    first, *rest = call.args
    if first.keyword is not None or first.star:
        raise ValueError("asyncio.to_thread callable argument must be positional")
    return cst.Call(func=first.value, args=tuple(rest))


def _remove_param(params: cst.Parameters, name: str) -> cst.Parameters:
    return params.with_changes(
        params=tuple(param for param in params.params if param.name.value != name)
    )


def _is_download_transport_assignment(statement: cst.SimpleStatementLine) -> bool:
    if len(statement.body) != 1:
        return False
    assignment = statement.body[0]
    if not isinstance(assignment, cst.Assign) or len(assignment.targets) != 1:
        return False
    target = assignment.targets[0].target
    if not (
        isinstance(target, cst.Attribute)
        and _is_name(target.value, "self")
        and target.attr.value == "_download_transport"
    ):
        return False
    return _is_name(assignment.value, "download_transport")


def _single_subscript_value(node: cst.Subscript) -> cst.BaseExpression | None:
    return _nth_subscript_value(node, 0) if len(node.slice) == 1 else None


def _nth_subscript_value(node: cst.Subscript, index: int) -> cst.BaseExpression | None:
    if index >= len(node.slice):
        return None
    element = node.slice[index]
    if not isinstance(element.slice, cst.Index):
        return None
    return element.slice.value


def _rewrite_module_docstring(module: cst.Module) -> cst.Module:
    if not module.body:
        return module
    first = module.body[0]
    rewritten = _rewrite_docstring_statement(first)
    if rewritten is first:
        return module
    return module.with_changes(body=(rewritten, *module.body[1:]))


def _rewrite_docstring_in_suite(suite: cst.BaseSuite) -> cst.BaseSuite:
    if not isinstance(suite, cst.IndentedBlock) or not suite.body:
        return suite
    first = suite.body[0]
    rewritten = _rewrite_docstring_statement(first)
    if rewritten is first:
        return suite
    return suite.with_changes(body=(rewritten, *suite.body[1:]))


def _rewrite_docstring_statement(
    statement: cst.BaseStatement,
) -> cst.BaseStatement:
    if not isinstance(statement, cst.SimpleStatementLine) or len(statement.body) != 1:
        return statement
    expr = statement.body[0]
    if not isinstance(expr, cst.Expr) or not isinstance(expr.value, cst.SimpleString):
        return statement

    value = expr.value.value
    updated = value
    for old, new in DOCSTRING_REPLACEMENTS:
        updated = updated.replace(old, new)
    if updated == value:
        return statement

    return statement.with_changes(
        body=(expr.with_changes(value=expr.value.with_changes(value=updated)),)
    )


def _format_source(source: str, target: Path, repo_root: Path) -> str:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_root = Path(tmp)
        tmp_path = tmp_root / target
        tmp_path.parent.mkdir(parents=True, exist_ok=True)
        _ = tmp_path.write_text(source, newline="")
        _run_ruff_fix([tmp_path], cwd=repo_root)
        return tmp_path.read_text()


def _run_ruff_fix(paths: Iterable[Path], cwd: Path = REPO_ROOT) -> None:
    path_args = [str(path) for path in paths]
    if not path_args:
        return

    _run(
        ["uv", "run", "ruff", "check", "--fix", "--select", "F401,I", *path_args],
        cwd=cwd,
    )
    _run(["uv", "run", "ruff", "format", *path_args], cwd=cwd)


def _run(command: list[str], cwd: Path) -> None:
    result = subprocess.run(command, cwd=cwd, text=True, capture_output=True)
    if result.returncode == 0:
        return
    _ = sys.stdout.write(result.stdout)
    _ = sys.stderr.write(result.stderr)
    raise subprocess.CalledProcessError(
        result.returncode,
        command,
        output=result.stdout,
        stderr=result.stderr,
    )


def _diff(actual: str, expected: str, target: Path) -> list[str]:
    return list(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"{target} (current)",
            tofile=f"{target} (generated)",
        )
    )


if __name__ == "__main__":
    if shutil.which("uv") is None:
        raise SystemExit("uv is required to run sync code generation")
    raise SystemExit(main())
