"""Public domain models and typed request/response helpers."""

import warnings
from typing import TYPE_CHECKING

from ksef2._domain.models.base import KSeFBaseModel, KSeFBaseParams
from ksef2._domain.models.compression import CompressionType, CompressionTypeEnum
from ksef2._domain.models.session import (
    BaseSessionResumeState,
    FormSchema,
    InvoiceStatusInfo,
    ListSessionsResponse,
    OpenOnlineSessionRequest,
    OpenOnlineSessionResponse,
    OnlineSessionResumeState,
    SessionEncryptionMaterial,
    SessionInvoiceStatusResponse,
    SessionInvoicesResponse,
    SessionStatusResponse,
    SessionSummary,
    Upo,
    UpoPage,
    deprecation_message,
)
from ksef2._domain.models.batch import (
    BatchEncryptionData,
    BatchFileInfo,
    BatchFilePart,
    BatchInvoice,
    BatchInvoiceHash,
    BatchPreparedPart,
    OpenBatchSessionRequest,
    BatchSessionResumeState,
    OpenBatchSessionResponse,
    PartUploadRequest,
    PreparedBatch,
)
from ksef2._domain.models.invoices import (
    BuyerIdentifierType,
    ExportHandle,
    ExportInvoicesPayload,
    ExportInvoicesResponse,
    ExportStatusInfo,
    InvoiceExportStatusResponse,
    InvoiceMetadata,
    InvoiceMetadataAuthorizedSubject,
    InvoiceMetadataBuyer,
    InvoiceMetadataBuyerIdentifier,
    InvoiceMetadataSeller,
    InvoiceMetadataThirdSubject,
    InvoiceMetadataThirdSubjectIdentifier,
    InvoicePackage,
    InvoicesFilter,
    InvoiceType,
    InvoicingMode,
    PackagePart,
    QueryInvoicesMetadataResponse,
    SendInvoicePayload,
    SendInvoiceResponse,
    SortOrder,
    ThirdSubjectIdentifierType,
)
from ksef2._domain.models.collective_identifiers import (
    CollectiveIdentifierInvoice,
    CollectiveIdentifierInvoiceDetails,
    CollectiveIdentifierInvoicePayment,
    CollectiveIdentifierInvoicesPage,
    CollectiveIdentifierInvoicesQuery,
    CollectiveIdentifierReference,
    CollectiveIdentifierReferencesPage,
    CollectiveIdentifierSummary,
    CollectiveIdentifiersPage,
    CollectiveIdentifiersQuery,
    GenerateCollectiveIdentifierResponse,
)
from ksef2._domain.models.permissions import (
    AttachmentPermissionStatus,
    AuthorizationGrantDetail,
    AuthorizationPermissionsQuery,
    AuthorizationPermissionsQueryResponse,
    AuthorizationPermissionType,
    AuthorizationSubjectIdentifierType,
    CertificateSubjectIdentifierType,
    EntityPermission,
    EntityPermissionDetail,
    EntityPermissionType,
    EntityIdentifierType,
    EntityPermissionsContextIdentifierType,
    EntityPermissionsQuery,
    EntityPermissionsQueryResponse,
    EntityRole,
    EntityRolesResponse,
    EuEntityAdminContextIdentifierType,
    EuEntityPermission,
    EuEntityPermissionsQuery,
    EuEntityPermissionsQueryResponse,
    EuEntityPermissionType,
    EuEntityQueryPermissionType,
    GrantAuthorizationPermissionsRequest,
    GrantEntityPermissionsRequest,
    GrantEuEntityAdministrationRequest,
    GrantEuEntityPermissionsRequest,
    GrantIndirectPermissionsRequest,
    GrantPermissionsResponse,
    GrantPersonPermissionsRequest,
    GrantSubunitPermissionsRequest,
    IndirectPermissionType,
    IndirectTargetIdentifierType,
    OperationStatus,
    OperationStatusCode,
    PermissionOperationStatusResponse,
    PermissionState,
    PersonalPermissionDetail,
    PersonalPermissionsAuthorizedIdentifierType,
    PersonalPermissionsContextIdentifierType,
    PersonalPermissionsQuery,
    PersonalPermissionsQueryResponse,
    PersonalPermissionsTargetIdentifierType,
    PersonalPermissionScope,
    PersonPermissionDetail,
    PersonAuthorIdentifierType,
    PersonContextIdentifierType,
    PersonPermissionsAuthorizedIdentifierType,
    PersonPermissionsContextIdentifierType,
    PersonPermissionsQuery,
    PersonPermissionsQueryResponse,
    PersonPermissionsTargetIdentifierType,
    PersonPermissionsQueryType,
    PersonPermissionScope,
    QueryType,
    SubordinateEntityRoleDetail,
    SubordinateEntityRolesQuery,
    SubordinateEntityRolesQueryResponse,
    SubordinateEntityRoleType,
    SubunitIdentifierType,
    SubunitPermission,
    SubunitPermissionsQuery,
    SubunitPermissionsQueryResponse,
)
from ksef2._domain.models.testdata import (
    AuthContextIdentifier,
    AuthContextIdentifierType,
    BlockContextRequest,
    CreatePersonRequest,
    CreateSubjectRequest,
    DeletePersonRequest,
    DeleteSubjectRequest,
    EnableAttachmentsRequest,
    Identifier,
    IdentifierType,
    Permission,
    PermissionType,
    GrantPermissionsRequest,
    RevokeAttachmentsRequest,
    RevokePermissionsRequest,
    SubjectType,
    SubUnit,
    UnblockContextRequest,
    UpdateCertificateRequest,
)
from ksef2._domain.models.tokens import (
    QueryTokensResponse,
    TokenAuthorIdentifier,
    TokenAuthorIdentifierType,
    TokenContextIdentifier,
    TokenContextIdentifierType,
    TokenInfo,
    TokenPermission,
    TokenStatus,
)
from ksef2._domain.models.auth import (
    AuthenticationMethodCategory,
    AuthenticationMethod,
    AuthenticationResumeState,
    AuthenticationSession,
    AuthenticationSessionsResponse,
    AuthInitResponse,
    AuthOperationStatus,
    AuthTokens,
    ChallengeResponse,
    ContextIdentifierType,
    InitTokenAuthenticationRequest,
    RefreshedToken,
    TokenCredentials,
)
from ksef2._domain.models.certificates import (
    CertificateEnrollmentData,
    CertificateInfo,
    CertificateLimitsResponse,
    CertificateStatusValue,
    CertificateTypeValue,
)
from ksef2._domain.models.limits import (
    ApiRateLimits,
    CollectiveIdentifierLimits,
    ContextLimits,
    SessionLimits,
    SubjectLimits,
)
from ksef2._domain.models.peppol import (
    PeppolProvider,
    ListPeppolProvidersResponse,
)
from ksef2._domain.models.pagination import (
    CollectiveIdentifierParams,
    InvoiceMetadataParams,
)

if TYPE_CHECKING:
    BaseSessionState = BaseSessionResumeState
    OnlineSessionState = OnlineSessionResumeState
    BatchSessionState = BatchSessionResumeState


_DEPRECATED_EXPORTS = {
    "BaseSessionState": (
        BaseSessionResumeState,
        deprecation_message(
            "ksef2._domain.models.BaseSessionState", "BaseSessionResumeState"
        ),
    ),
    "OnlineSessionState": (
        OnlineSessionResumeState,
        deprecation_message(
            "ksef2._domain.models.OnlineSessionState", "OnlineSessionResumeState"
        ),
    ),
    "BatchSessionState": (
        BatchSessionResumeState,
        deprecation_message(
            "ksef2._domain.models.BatchSessionState", "BatchSessionResumeState"
        ),
    ),
}


def __getattr__(name: str) -> object:
    if name in _DEPRECATED_EXPORTS:
        value, message = _DEPRECATED_EXPORTS[name]
        warnings.warn(message, DeprecationWarning, stacklevel=2)
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    # base
    "KSeFBaseModel",
    "KSeFBaseParams",
    "CompressionType",
    "CompressionTypeEnum",
    # session
    "BaseSessionResumeState",
    "FormSchema",
    "InvoiceStatusInfo",
    "ListSessionsResponse",
    "OpenOnlineSessionRequest",
    "OpenOnlineSessionResponse",
    "OnlineSessionResumeState",
    "SessionEncryptionMaterial",
    "SessionInvoiceStatusResponse",
    "SessionInvoicesResponse",
    "SessionStatusResponse",
    "SessionSummary",
    "Upo",
    "UpoPage",
    # batch
    "BatchFileInfo",
    "BatchFilePart",
    "BatchInvoice",
    "BatchInvoiceHash",
    "BatchPreparedPart",
    "BatchEncryptionData",
    "OpenBatchSessionRequest",
    "BatchSessionResumeState",
    "OpenBatchSessionResponse",
    "PartUploadRequest",
    "PreparedBatch",
    # invoices
    "ExportHandle",
    "BuyerIdentifierType",
    "ExportInvoicesPayload",
    "ExportInvoicesResponse",
    "ExportStatusInfo",
    "FormSchema",
    "InvoiceExportStatusResponse",
    "InvoiceMetadata",
    "InvoiceMetadataAuthorizedSubject",
    "InvoiceMetadataBuyer",
    "InvoiceMetadataBuyerIdentifier",
    "InvoiceMetadataSeller",
    "InvoiceMetadataThirdSubject",
    "InvoiceMetadataThirdSubjectIdentifier",
    "InvoiceMetadataParams",
    "InvoicePackage",
    "InvoicesFilter",
    "InvoiceType",
    "InvoicingMode",
    "PackagePart",
    "QueryInvoicesMetadataResponse",
    "SendInvoicePayload",
    "SendInvoiceResponse",
    "SortOrder",
    "ThirdSubjectIdentifierType",
    # collective identifiers
    "CollectiveIdentifierInvoice",
    "CollectiveIdentifierInvoiceDetails",
    "CollectiveIdentifierInvoicePayment",
    "CollectiveIdentifierInvoicesPage",
    "CollectiveIdentifierInvoicesQuery",
    "CollectiveIdentifierParams",
    "CollectiveIdentifierReference",
    "CollectiveIdentifierReferencesPage",
    "CollectiveIdentifierSummary",
    "CollectiveIdentifiersPage",
    "CollectiveIdentifiersQuery",
    "GenerateCollectiveIdentifierResponse",
    # permissions
    "AttachmentPermissionStatus",
    "AuthorizationGrantDetail",
    "AuthorizationPermissionsQuery",
    "AuthorizationPermissionsQueryResponse",
    "AuthorizationPermissionType",
    "AuthorizationSubjectIdentifierType",
    "CertificateSubjectIdentifierType",
    "EntityPermission",
    "EntityPermissionDetail",
    "EntityPermissionType",
    "EntityIdentifierType",
    "EntityPermissionsContextIdentifierType",
    "EntityPermissionsQuery",
    "EntityPermissionsQueryResponse",
    "EntityRole",
    "EntityRolesResponse",
    "EuEntityAdminContextIdentifierType",
    "EuEntityPermission",
    "EuEntityPermissionsQuery",
    "EuEntityPermissionsQueryResponse",
    "EuEntityPermissionType",
    "EuEntityQueryPermissionType",
    "GrantAuthorizationPermissionsRequest",
    "GrantEntityPermissionsRequest",
    "GrantEuEntityAdministrationRequest",
    "GrantEuEntityPermissionsRequest",
    "GrantIndirectPermissionsRequest",
    "GrantPermissionsResponse",
    "GrantPersonPermissionsRequest",
    "GrantSubunitPermissionsRequest",
    "IndirectPermissionType",
    "IndirectTargetIdentifierType",
    "OperationStatus",
    "OperationStatusCode",
    "PermissionOperationStatusResponse",
    "PermissionState",
    "PersonalPermissionDetail",
    "PersonalPermissionsAuthorizedIdentifierType",
    "PersonalPermissionsContextIdentifierType",
    "PersonalPermissionsQuery",
    "PersonalPermissionsQueryResponse",
    "PersonalPermissionsTargetIdentifierType",
    "PersonalPermissionScope",
    "PersonPermissionDetail",
    "PersonAuthorIdentifierType",
    "PersonContextIdentifierType",
    "PersonPermissionsAuthorizedIdentifierType",
    "PersonPermissionsContextIdentifierType",
    "PersonPermissionsQuery",
    "PersonPermissionsQueryResponse",
    "PersonPermissionsTargetIdentifierType",
    "PersonPermissionsQueryType",
    "PersonPermissionScope",
    "QueryType",
    "SubordinateEntityRoleDetail",
    "SubordinateEntityRolesQuery",
    "SubordinateEntityRolesQueryResponse",
    "SubordinateEntityRoleType",
    "SubunitIdentifierType",
    "SubunitPermission",
    "SubunitPermissionsQuery",
    "SubunitPermissionsQueryResponse",
    # testdata
    "AuthContextIdentifier",
    "AuthContextIdentifierType",
    "BlockContextRequest",
    "CreatePersonRequest",
    "CreateSubjectRequest",
    "DeletePersonRequest",
    "DeleteSubjectRequest",
    "EnableAttachmentsRequest",
    "Identifier",
    "IdentifierType",
    "Permission",
    "PermissionType",
    "GrantPermissionsRequest",
    "RevokeAttachmentsRequest",
    "RevokePermissionsRequest",
    "SubjectType",
    "SubUnit",
    "UnblockContextRequest",
    "UpdateCertificateRequest",
    # tokens
    "QueryTokensResponse",
    "TokenAuthorIdentifier",
    "TokenAuthorIdentifierType",
    "TokenContextIdentifier",
    "TokenContextIdentifierType",
    "TokenInfo",
    "TokenPermission",
    "TokenStatus",
    # auth
    "AuthenticationMethodCategory",
    "AuthenticationMethod",
    "AuthenticationResumeState",
    "AuthenticationSession",
    "AuthenticationSessionsResponse",
    "AuthInitResponse",
    "AuthOperationStatus",
    "AuthTokens",
    "ChallengeResponse",
    "ContextIdentifierType",
    "InitTokenAuthenticationRequest",
    "RefreshedToken",
    "TokenCredentials",
    # certificates
    "CertificateEnrollmentData",
    "CertificateInfo",
    "CertificateLimitsResponse",
    "CertificateStatusValue",
    "CertificateTypeValue",
    # limits
    "ApiRateLimits",
    "CollectiveIdentifierLimits",
    "ContextLimits",
    "SessionLimits",
    "SubjectLimits",
    # peppol
    "PeppolProvider",
    "ListPeppolProvidersResponse",
]
