from ksef2.infra.mappers.helpers import to_aware_datetime
from collections.abc import Sequence
from datetime import date, datetime
from decimal import Decimal
from typing import Self

from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig

from ksef2.domain.models.fa3 import (
    ContactInfo,
    InvoiceAddress,
    InvoiceEntity,
    InvoiceHeader,
    InvoiceLine,
    KsefInvoice,
    KsefInvoiceBody,
)
from ksef2.domain.models.fa3.body import InvoiceType, SaleCategory, VatRate
from ksef2.infra.mappers.invoices.fa3.invoice import to_spec as invoice_to_spec
from ksef2.infra.schema.fa3.models.schemat import Faktura, __NAMESPACE__


class FA3InvoiceBuilder:
    """Stepwise helper for constructing a complete FA(3) invoice aggregate."""

    def __init__(self) -> None:
        self._header: InvoiceHeader | None = InvoiceHeader()
        self._seller: InvoiceEntity | None = None
        self._buyer: InvoiceEntity | None = None
        self._body: KsefInvoiceBody | None = None
        self._lines: list[InvoiceLine] = []

    def header(
        self, *, generation_timestamp: datetime | str | None = None, system_info: str
    ) -> Self:
        self._header = InvoiceHeader(
            generation_timestamp=to_aware_datetime(
                generation_timestamp or datetime.now()
            ),
            system_info=system_info,
        )
        return self

    def seller(
        self,
        *,
        name: str,
        country_code: str,
        address_line_1: str,
        tax_id: str | None = None,
        address_line_2: str | None = None,
        gln: str | None = None,
        eu_vat_id: str | None = None,
        customer_number: str | None = None,
        email: str | None = None,
        phone: str | None = None,
    ) -> Self:
        self._seller = self._build_entity(
            name=name,
            country_code=country_code,
            address_line_1=address_line_1,
            tax_id=tax_id,
            address_line_2=address_line_2,
            gln=gln,
            eu_vat_id=eu_vat_id,
            customer_number=customer_number,
            email=email,
            phone=phone,
        )
        return self

    def buyer(
        self,
        *,
        name: str,
        country_code: str,
        address_line_1: str,
        tax_id: str | None = None,
        address_line_2: str | None = None,
        gln: str | None = None,
        eu_vat_id: str | None = None,
        customer_number: str | None = None,
        email: str | None = None,
        phone: str | None = None,
    ) -> Self:
        self._buyer = self._build_entity(
            name=name,
            country_code=country_code,
            address_line_1=address_line_1,
            tax_id=tax_id,
            address_line_2=address_line_2,
            gln=gln,
            eu_vat_id=eu_vat_id,
            customer_number=customer_number,
            email=email,
            phone=phone,
        )
        return self

    def body(
        self,
        *,
        issue_date: date,
        currency: str = "PLN",
        issue_place: str | None = None,
        invoice_type: InvoiceType | str = InvoiceType.VAT,
        warehouse_documents: Sequence[str] | None = None,
        date_of_supply: date | None = None,
        period_start: date | None = None,
        period_end: date | None = None,
    ) -> Self:

        if not self._lines:
            raise ValueError(
                "Cannot build FA(3) invoice body without any invoice lines"
            )

        # [TODO] invoice number is currently autogenerated
        # but should be created based on the last invoice number saved in the database
        self._body = KsefInvoiceBody(
            currency=currency,
            issue_place=issue_place,
            issue_date=issue_date,
            invoice_type=self._coerce_invoice_type(invoice_type),
            warehouse_documents=list(warehouse_documents or []),
            date_of_supply=date_of_supply,
            period_start=period_start,
            period_end=period_end,
            lines=self._lines,
        )

        return self

    def add_line(
        self,
        *,
        name: str,
        quantity: Decimal,
        unit_price_net: Decimal,
        vat_rate: VatRate | str | None = None,
        unit_of_measure: str = "szt",
        supply_date: date | None = None,
        discount_amount: Decimal | None = Decimal("0.00"),
        sale_category: SaleCategory | str = SaleCategory.STANDARD,
        net_amount: Decimal | None = None,
        vat_amount: Decimal | None = None,
        gross_amount: Decimal | None = None,
        unique_id: str | None = None,
        sku: str | None = None,
        gtin: str | None = None,
        pkwiu: str | None = None,
        cn: str | None = None,
        pkob: str | None = None,
        before_correction: bool = False,
    ) -> Self:
        self._lines.append(
            InvoiceLine(
                name=name,
                quantity=quantity,
                unit_price_net=unit_price_net,
                vat_rate=self._coerce_vat_rate(vat_rate),
                unit_of_measure=unit_of_measure,
                supply_date=supply_date,
                discount_amount=discount_amount,
                sale_category=self._coerce_sale_category(sale_category),
                net_amount=net_amount,
                vat_amount=vat_amount,
                gross_amount=gross_amount,
                unique_id=unique_id,
                sku=sku,
                gtin=gtin,
                pkwiu=pkwiu,
                cn=cn,
                pkob=pkob,
                before_correction=before_correction,
            )
        )
        return self

    def add_line_model(self, line: InvoiceLine) -> Self:
        self._lines.append(line)
        return self

    def replace_lines(self, lines: Sequence[InvoiceLine]) -> Self:
        self._lines = list(lines)
        return self

    def clear_lines(self) -> Self:
        self._lines = []
        return self

    def missing_steps(self) -> list[str]:
        missing: list[str] = []
        if self._seller is None:
            missing.append("seller")
        if self._buyer is None:
            missing.append("buyer")
        if not self._body:
            missing.append("body")
        if not self._lines:
            missing.append("lines")
        return missing

    def is_ready(self) -> bool:
        return not self.missing_steps()

    def build(self) -> KsefInvoice:
        missing_steps = self.missing_steps()
        if missing_steps:
            raise ValueError(
                f"Cannot build FA(3) invoice. Missing steps: {', '.join(missing_steps)}"
            )

        assert self._header is not None
        assert self._seller is not None
        assert self._buyer is not None
        assert self._body is not None

        return KsefInvoice(
            invoice_header=self._header,
            seller=self._seller,
            buyer=self._buyer,
            body=self._body,
        )

    def to_spec(self) -> Faktura:
        return invoice_to_spec(self.build())

    def to_xml(
        self,
        *,
        pretty_print: bool = True,
        xml_declaration: bool = True,
        encoding: str = "UTF-8",
    ) -> str:
        serializer = XmlSerializer(
            config=SerializerConfig(
                pretty_print=pretty_print,
                xml_declaration=xml_declaration,
                encoding=encoding,
            )
        )
        return serializer.render(
            self.to_spec(),
            ns_map={None: __NAMESPACE__},
        )

    @staticmethod
    def _build_entity(
        *,
        name: str,
        country_code: str,
        address_line_1: str,
        tax_id: str | None,
        address_line_2: str | None,
        gln: str | None,
        eu_vat_id: str | None,
        customer_number: str | None,
        email: str | None,
        phone: str | None,
    ) -> InvoiceEntity:
        contact = ContactInfo(email=email, phone=phone) if email or phone else None
        return InvoiceEntity(
            tax_id=tax_id,
            eu_vat_id=eu_vat_id,
            customer_number=customer_number,
            name=name,
            address=InvoiceAddress(
                country_code=country_code,
                address_line_1=address_line_1,
                address_line_2=address_line_2,
                gln=gln,
            ),
            contact=contact,
        )

    @staticmethod
    def _coerce_invoice_type(value: InvoiceType | str) -> InvoiceType:
        if isinstance(value, InvoiceType):
            return value
        return InvoiceType(value)

    @staticmethod
    def _coerce_vat_rate(value: VatRate | str | None) -> VatRate | None:
        if value is None or isinstance(value, VatRate):
            return value
        try:
            return VatRate(value)
        except ValueError as exc:
            raise ValueError(
                f"Provided VAT rate: `{value}` is not valid `VatRate` enum member. "
                f"Valid choices are: {', '.join(VatRate.__members__.keys())}"
            ) from exc

    @staticmethod
    def _coerce_sale_category(value: SaleCategory | str) -> SaleCategory:
        if isinstance(value, SaleCategory):
            return value
        try:
            return SaleCategory(value)
        except ValueError as exc:
            raise ValueError(
                f"Provided sale category: `{value}` is not valid `SaleCategory` enum member. "
                f"Valid choices are: {', '.join(SaleCategory.__members__.keys())}"
            ) from exc
